/*
 * genCuratedNames — the WRITING layer for Gen Curated.
 *
 * Deep, hand-authored caption pools so a curated set's little synopsis never
 * reads the same way twice. The recipe engine (genCurated.ts) picks a feasible
 * SET, then pulls a caption from the matching pool here. Pools are intentionally
 * large — the variance is the charm.
 *
 * Strings are double-quoted so apostrophes pass through untouched.
 */

import type { ColorBucket } from '../art/outputColor';

/* ── Mono-colour walls — ~100 per bucket ───────────────────────────────── */
export const COLOR_NAMES: Record<ColorBucket, string[]> = {
    Hothurt: ["Branding Iron","Hot Pink Steel","Searing Pink","Neon Burn","Electric Fuchsia","Pink Inferno","Magenta Heat","It Hurts","Scald","Plasma Pink","Hot To Touch","Fuchsia Flare","Burnt Tongue","Third Degree","Sizzle Pink","Pink Plasma","Hotter","Welt","Flamingo Fever","Pink Lightning","Sunburn Pink","Raw Nerve","Live Wire","Singe","Pink Voltage","Cauterize","Blister","Heat Death","Fever Pink","Pink Scream","Too Hot","Searbright","Molten Rose","Pink Filament","Neon Wound","Volt Pink","Pink Furnace","Char Rose","Pink Static","Ouch","Hot Coal Rose","Pink Ember","Stinging Pink","Atomic Pink","Pink Flashbang","Radiant Burn","Pink Tinnitus","Sear Line","Hot Filament","Glowing Pink","White Hot Pink","Pink Arc","Burnpink","Fuchsia Fever","Pink Pylon","Shock Pink","Heat Rash","Pink Brand","Combust","Pink Migraine","Raw Pink","Pink Sunstroke","Overheat","Magenta Burn","Pink Strobe","Searcore","Pink Solder","Nerve Pink","Flare Up","Hot Iron Rose","Pink Reactor","Stovetop Pink","Pink Klaxon","Neon Scar","Pink Supernova","Hot Bloom","Pink Tantrum","Flash Pink","Fuchsia Scald","Pink Wattage","Bare Wire Pink","Pink Cinder","Heatstroke Rose","Searing Rose","Pink Alarm","Burning Bright","Hot Glow Rose","Pink Razor","Throbbing Pink","Pink Ignition","Sting","Fuchsia Furnace","Pink Bonfire","Hot Neon","Magenta Sear","Pink Whiteout","Branded Rose","Hurts So Hot","Pinkest Burn"],
    Red: ["Blood Orange","Crimson Tide","Scarlet Letter","Red Alert","Cherry Bomb","Ruby Slippers","Garnet","Rouge","Vermilion","Carmine","Brick House","Rust Belt","Pomegranate","Fire Engine","Red Velvet","Maraschino","Stop Sign","Cardinal Sin","Burgundy","Oxblood","Claret","Sangria","Merlot","Beet Red","Chili","Paprika","Cinnabar","Red Giant","Lipstick","Devil Red","Seeing Red","Red Right Hand","Code Red","Red October","Mars Red","Red Planet","Rose Madder","Hot Sauce","Hellfire","Cranberry","Currant","Raspberry","Strawberry","Tomato","Apple Red","Red Delicious","Wine Dark","Bordeaux","Cabernet","Red Earth","Terracotta","Sienna","Coral Red","Salsa","Ladybug","Poppy","Geranium","Red Carpet","Matador","Bullfight","Cherry Cola","Redrum","Lifeblood","Arterial","Henna","Madder Root","Vermeil","Russet","Berry","Redshift","Carnelian","Jasper","Red Flag","Stoplight","Firetruck","Red Sky","Sunset Red","Dragon Red","Lacquer","Cinnamon Red","Crimson Peak","Red Room","Rubicon","Red String","Blood Moon","Scarlet Fever","Crimson King","Valentine","Cherry Pop","Red Heat","Red Carnation","Tabasco","Chili Pepper","Pimento","Roman Red","Punch","Sealing Wax","Red Lacquer","Carmine Wave"],
    Orange: ["Tangerine Dream","Clementine","Sunset Boulevard","Burnt Orange","Marmalade","Apricot","Persimmon","Saffron","Amber Wave","Pumpkin Spice","Carrot Top","Cantaloupe","Mango","Papaya","Tiger Lily","Monarch","Citrus","Valencia","Honey Crisp","Copper","Ginger","Marigold","Nasturtium","Coral Reef","Salmon Run","Sunkist","Orange Crush","Creamsicle","Cheeto Dust","Traffic Cone","Safety Orange","Hazard","High Vis","Construction","Fox Fur","Vulpine","Ember","Hearth","Bonfire","Autumn Leaf","Harvest","Cider","Pumpkin Patch","Jack O Lantern","Halloween","Terracotta Pot","Clay","Adobe","Desert Sun","Mojave","Sahara","Spice Market","Turmeric","Cayenne","Habanero","Sweet Potato","Butternut","Squash Blossom","Goldfish","Koi","Carnelian Glow","Sunstone","Fire Opal","Topaz Heat","Aperol","Spritz","Campari","Negroni","Mimosa Sunrise","Orange Julius","Fanta","Dreamsicle","Peach Melba","Nectarine","Loquat","Kumquat","Burnt Sienna","Raw Sienna","Ochre","Rust Bloom","Vermilion Sun","Flame","Torch","Lantern","Sunset Strip","Golden Hour","Magic Hour","Tangelo","Satsuma","Orange Peel","Zest","Rind","Molten Copper","Brass Heat","Amber Ale","Caramel","Toffee"],
    Yellow: ["Lemon Drop","Goldenrod","Sunflower","Buttercup","Canary","Dandelion","Mellow Yellow","Banana Cream","Honey","Mustard","Dijon","Saffron Thread","Corn Silk","Maize","Butter","Custard","Daffodil","Citrine","Topaz","Amber Light","Honeycomb","Beeswax","Pollen","Lemon Zest","Limoncello","Pineapple","Mango Lassi","Egg Yolk","Yolk","Sunny Side","Highlighter","Caution","Taxi Cab","School Bus","No 2 Pencil","Legal Pad","Post It","Rubber Duck","Tweety","Big Bird","Pikachu","Minion","Smiley","Gold Leaf","Bullion","24 Karat","Brass","Old Gold","Champagne","Chardonnay","Straw","Wheat Field","Hay","Sand Dune","Desert Gold","Sunbeam","Daylight","High Noon","Solar Flare","Sunshower","Buttermilk","Lemon Curd","Meyer Lemon","Citron","Chartreuse","Acid Yellow","Neon Lemon","Electric Yellow","Sulfur","Brimstone","Flax","Naples Yellow","Chrome Yellow","Cadmium","Gamboge","Saffron Gold","Wattle","Forsythia","Primrose","Cowslip","Jonquil","Buttercream","Lemon Meringue","Banana Split","Golden Hour Glow","Glow Stick","Firefly","Candlelight","Bee Pollen","Golden Fleece","Sun King","Marigold Bright","Pale Gold","Sunlit","Amber Glow","Lemonade","Goldeneye"],
    Green: ["Verdigris","Chlorophyll","Absinthe","Patina","Malachite","Sea Glass","Emerald City","Greenhouse","Moss Agate","Chartreuse","Pistachio","Shamrock","Jade Dynasty","Forest Floor","Olive Branch","Green Room","Bottle Green","Pine Fresh","Mint Condition","Celadon","Viridian","Sage Advice","Clover","Fern Gully","Hunter Green","Kelly Green","Avocado Toast","Matcha Hour","Greenback","Lush","Photosynthesis","Algae Bloom","Peridot","Limelight","Reptile","Pickle","Wasabi","Kale Yeah","Greener Pastures","Emerald Isle","Bamboo","Terrarium","Lily Pad","Frog Chorus","Basil","Cucumber Cool","Pesto","Mojito","Green Flash","Glow Worm","Northern Lights","Envy","Go Green","Loden","Fairway","Spirulina","Seaweed","Pondlife","Evergreen","Mantis","Luna Moth","Ivy League","Topiary","Cactus","Succulent","Verde","Jungle Floor","Canopy","Mossy Bank","Gecko","Green Screen","Hulk Mode","Slime Time","Neon Lichen","Acid Wash","Toxic","Radioactive","Swamp","Brat","Green Day","Money Tree","Dollar Bill","Jade Buddha","Khaki Drift","Army Surplus","Camo","Sour Apple","Granny Smith","Lime Twist","Key Lime","Honeydew","Spearmint","Wintergreen","Eucalyptus","Tea Leaf","Pea Soup","Emerald Cut","Verdant","Fresh Cut"],
    Blue: ["Blue Hour","Deep Blue","Feeling Blue","Sapphires","Cyanotype","Indigo Child","Cobalt","Ultramarine","Azure","Cerulean","Navy Pier","Prussian Blue","Lapis Lazuli","Bluebird","Forget Me Not","Open Water","Tidal","Midnight Blue","Electric Blue","Cornflower","Periwinkle","Denim Days","True Blue","Blue Note","Rhapsody In Blue","Picasso Blue","Klein Blue","Blue Period","Bluebell","Sky High","Stratosphere","Robin Egg","Teal Appeal","Aquamarine","Glacier","Iceberg","Frostbite","Arctic","Blue Steel","Out Of The Blue","Bayou Blue","Deep Dive","Mariana","Abyss","Blue Velvet","Bruise","Blue Monday","Blue Moon","Powder Blue","Baby Blue","Steel Blue","Slate","Stormcloud","Twilight","Dusk","Nightfall","Cosmic Blue","Cyan Wave","Turquoise","Tiffany","Peacock","Kingfisher","Blue Jay","Sailor","Naval","Maritime","Riptide","Lagoon","Caribbean","Pool Party","Chlorine","Cold Front","Blue Flame","Gas Burner","Pilot Light","Bluescreen","Y2K Blue","Windows Blue","Blueprint","Ink Spill","Fountain Pen","Royal Blue","Delft","Porcelain","Wedgwood","China Blue","Blue Curacao","Blueberry","Bilberry","Cool Blue","Sub Zero","Blue Streak","Mood Indigo","Blue Hawaii","Pacific","Horizon","Deep End","Cyan Sea"],
    Purple: ["Purple Reign","Royal Purple","Amethyst","Violet Hour","Lavender Haze","Ultraviolet","Aubergine","Plum Job","Mauve","Lilac","Wisteria","Orchid","Heliotrope","Byzantium","Tyrian","Imperial","Crown Jewels","Grape Soda","Eggplant","Concord","Purple Rain","Prince","Deep Purple","Jacaranda","Iris","Thistle","Heather","Foxglove","Crocus","Hyacinth","Mulberry","Boysenberry","Blackberry","Plum Wine","Cassis","Damson","Sugarplum","Fig","Magenta Drift","Royalty","Bishop","Cardinal Robe","Velvet Throne","Purple Velvet","Twilight Violet","Dusk Petal","Mystic","Third Eye","Crystal Grid","Amethyst Geode","Sugilite","Charoite","Tanzanite","Lepidolite","Fluorite","Purple Haze","Hendrix","Codeine Dream","Pixel Violet","Vaporwave","Synthwave","Neon Violet","Electric Violet","Blacklight","Ultraviolet Ray","UV Index","Bruised Plum","Pansy","Violet Beauregarde","Grape Crush","Purple People","Thanos","Infinity Stone","Nebula","Galaxy","Stardust Violet","Lilac Sky","Lavender Field","Provence","Lupine","Petunia","Clematis","Verbena","Violet Femme","Grape Vine","Royal Velvet","Plumage","Indigo Edge","Purple Patch","Deep Violet","Velvet","Amethyst Hour","Orchid Bloom","Currant","Aster","Mystic Violet","Regal"],
    Magenta: ["Magenta Mood","Fuchsia","Hot Pink","Shocking Pink","Schiaparelli Pink","Magenta Hour","Electric Pink","Neon Pink","Hot Magenta","Bougainvillea","Fuchsia Flash","Pink Panther","Barbiecore","Barbie Pink","Raspberry","Razzmatazz","Cerise","Rose Madder","Cyclamen","Orchid Pink","Dragon Fruit","Pitaya","Prickly Pear","Cactus Flower","Bubblegum Pop","Cotton Candy","Pink Lemonade","Berry Blast","Cranberry Pop","Flamingo","Pink Flamingo","Watermelon","Tickled Pink","In The Pink","Pretty In Pink","Pink Slip","Pink Noise","Process Magenta","Printer Pink","CMYK Pink","Pixel Pink","Neon Sign","Vegas Pink","Motel Pink","Miami Vice","Vaporwave Pink","Synth Pink","Hyperpop","Brat Pink","Pink Friday","Lisa Frank","Trapper Keeper","Y2K Pink","Plastic Pink","Bubblegum","Fruit Punch","Punchy Pink","Beetroot","Radish","Peony","Azalea","Rhododendron","Camellia","Snapdragon","Hibiscus","Geranium","Pink Orchid","Magenta Bloom","Crushed Berry","Mulberry Crush","Loganberry","Jam Session","Pink Champagne","Rose Fizz","Negroni Pink","Sangria Pink","Cosmopolitan","Pink Gin","Strawberry Milk","Taffy","Saltwater Taffy","Lipstick","Hot Lips","Ruby Woo","Schiap Shock","Magenta Velvet","Electric Fuchsia","Pink Static","Shocking","Berry Bold","Fuchsia Plant","Crepe Myrtle","Pink Bloom","Neon Rose","Disco Pink","Pink Heat","Carnation","Watermelon Sugar","Pink Pop"],
    Brown: ["Burnt Umber","Raw Sienna","Espresso Shot","Dark Roast","Cold Brew","Mocha Pour","Cacao Nib","Bitter Cacao","Seventy Percent","Ganache","Terracotta","Baked Clay","Adobe Heat","Fired Earth","Old Leather","Saddle Worn","Tanned Hide","Bomber Jacket","Walnut Grain","Teak Finish","Mahogany Deep","Oak Aged","Driftwood","Cedar Dust","Pinecone","Acorn Fall","Chestnut Roast","Hazelnut","Pecan Butter","Almond Skin","Toasted Oat","Pumpernickel","Sourdough Crust","Gingerbread","Caramel Drip","Toffee Pull","Butterscotch","Maple Run","Molasses","Brown Sugar","Cinnamon Stick","Nutmeg","Clove Smoke","Coffee Ring","Tobacco Leaf","Cigar Box","Whiskey Neat","Bourbon Barrel","Rye Amber","Peat Smoke","Soil Rich","Loam","Topsoil","Peat Bog","Riverbank Mud","Earthenware","Rust Bloom","Sepia Tone","Old Photograph","Vintage Print","Faded Map","Tortoiseshell","Amber Resin","Tigereye","Smoky Quartz","Bronze Patina","Antique Brass","Penny Worn","Copper Tarnish","Umber Shadow","Van Dyck Brown","Burnt Sugar","Truffle","Hot Cocoa","Tiramisu","Affogato","Crema","Macchiato","Roasted Bean","Brick Dust","Henna","Russet","Chestnut Mare","Bay Horse","Fawn","Doe Skin","Camel Coat","Khaki Dust","Mink","Sable","Otter Pelt","Beaver Felt","Burnished","Earthbound","Grounded","Earth Tones","Chocolate Box","Coffee Run","Wood Grain"],
    Cream: ["Off White","Eggshell","Bone China","Old Ivory","Fresh Vanilla","Vanilla Bean","Clotted Cream","Whipped Soft","Buttermilk","Sweet Butter","Churned","Custard","Panna Cotta","Almond Milk","Oat Milk","Steamed Milk","Latte Foam","Flat White","Meringue Peak","Marshmallow","Nougat","White Chocolate","Shortbread","Sugar Cookie","Wedding Cake","Frosting","Royal Icing","Marzipan","Parchment","Vellum","Aged Paper","Manila","Linen Fold","Raw Cotton","Unbleached","Cashmere Soft","Wool Cream","Angora","Alabaster","Chalk White","Limestone","Sandstone Pale","Seashell","Pearl Matte","Mother of Pearl","Conch","Sand Dollar","Dune Pale","Beach Glass","Coconut Flesh","Macadamia","Cauliflower","Brie Rind","Camembert","Ricotta","Mascarpone","Buttercream","Lemon Curd","Honeycomb Wax","Beeswax","Tallow","Soap Bar","Antique White","Faded Lace","Wedding Dress","Doily","Porcelain","Fine Bone","Ecru","Greige Light","Putty","Oatmeal","Flour Dust","Powdered Sugar","Confection","Vanilla Sky","Pale Honey","Light Amber","Champagne Soft","Prosecco","Muslin","Calico","Tracing Paper","Notepaper","Ghost White","Soft Focus","Warm White","Candle Glow","Wax Seal","Pale Straw","Wheat Pale","Bisque","Magnolia","Buff","Natural Tone","Cream of the Crop","Soft Serve","Vanilla","Ivory Tower"],
    Moon: ["Moonlight","Full Moon","Harvest Moon","Crescent Glow","Lunar Pale","Moonstone","Selenite","Silver Sheen","Pewter Soft","Oyster Grey","Oyster Shell","Pale Pewter","Mercury","Quicksilver","Liquid Silver","Tin Glow","Cold Silver","Frost Silver","Moon Dust","Stardust Pale","Night Pearl","Pearl Glow","Opaline","Milk Glass","Glacier Pale","Ice Floe","Winter Sky","Pale Frost","Hoarfrost","First Snow","Snowmelt","Slush Grey","Fog Bank","Sea Mist","Morning Haze","Pale Vapour","Cloud Belly","Overcast Soft","Dove Grey","Pigeon","Mourning Dove","Ash Pale","Grey Pearl","Smoke Veil","Silk Grey","Satin Pewter","Pale Steel","Brushed Nickel","Platinum Soft","White Gold","Pale Chrome","Aluminium","Galvanised","Zinc","Wet Stone","Riverstone Pale","Bluestone Soft","Moonbeam","Night Light","Lantern Pale","Witching Hour","Twilight Silver","Dusk Glow","Cold Dawn","Pale Twilight","Eclipse Edge","Halo","Aura Pale","Spectral","Ghostlight","Phantom Pale","Silvered Glass","Mirror Soft","Pale Mercury","Lunar Sea","Sea of Calm","Crater Pale","Moon Rock","Lunar Dust","Pale Selene","Diana","Luna Soft","Waning Glow","Waxing Pale","Gibbous","Cold Moon","Wolf Moon","Snow Moon","Pale Orbit","Tidal Pull","Moonstruck","Pale Light","Eclipse","Tides","Lunar","Silver Glow","Nightfall Pale","New Moon"],
    Grey: ["Concrete","Wet Cement","Sidewalk","Brutalist","Poured Slab","Ash Grey","Cold Ash","Cigarette Ash","Volcanic Ash","Charcoal Soft","Smudged Graphite","Pencil Lead","Number Two","Smoke Stack","Chimney Soot","Exhaust","Diesel Cloud","Storm Front","Thunderhead","Gathering Storm","Squall","Grey Sky","Overcast","Drizzle","Wet Pavement","Monsoon Grey","Battleship","Gunmetal","Cold Steel","Brushed Steel","Tempered Steel","Anvil","Forged Iron","Wrought Grey","Slate","Slate Roof","Shale","Flint","Granite","Basalt","Pumice","Gravel","Macadam","Asphalt","Tarmac","Road Worn","Stone Cold","Headstone","Fossil","Pebble","Riverstone","Whetstone","Greyscale","Neutral Density","Mid Grey","Fifty Percent","Dove Tone","Mouse Grey","Field Mouse","Squirrel","Wolf Grey","Timberwolf","Heather Grey","Marl","Flannel","Tweed","Worsted","Pinstripe","Suit Grey","Steel Wool","Oxidised","Patina Grey","Lead Sheet","Zinc Roof","Static Snow","Television Snow","Dead Channel","Greyout","Fade to Grey","Ghost Grey","Shadow Grey","Penumbra","Eclipse Grey","Dusk Steel","Nimbus","Cumulus Grey","Foggy Bottom","Mist Grey","Silver Fox","Salt and Pepper","Steely Eyed","Graphite","Slate Pale","Battleship Grey","Ash and Smoke","Storm Grey","Concrete Jungle","Pewter"],
    Black: ["Noir","The Void","Onyx","Ink","Midnight","Eclipse","Obsidian","After Dark","Pitch","Carbon","Soot","Coal","Tar Pit","Blackout","Lights Out","Dead of Night","Vantablack","Jet","Sable","Ebony","Pure Black","All Black Everything","Total Eclipse","The Abyss","Event Horizon","Black Hole","Dark Matter","New Moon","Moonless","Starless","Raven","Crow","Black Cat","Witching Hour","Graveyard Shift","The Long Dark","Black Ice","Charcoal","Squid Ink","Licorice","Espresso","Black Coffee","Burnt","Ash","Smoke","Cinders","Shadow Work","Cast Shadow","Silhouette","Negative Space","Black Box","Redacted","Off the Grid","Power Cut","Cave Black","Underworld","The Deep End","Nightfall","Black Velvet","Black Tie","Little Black Dress","Men in Black","Back in Black","Paint It Black","Fade to Black","Black Mirror","Crude Oil","Slick","Crow Feather","Panther","Black Swan","Cellar","Blackest Night","Stygian","Noir Mode","Dark Mode","The Dark Side","Heart of Darkness","Inkwell","Spilled Ink","Wet Tar","Volcanic Glass","Lava Rock","Black Pearl","Black Gold","Black Sheep","Total Dark","Blacked Out","Pure Shade","Umbra","Black Onyx","Velvet Dark","Endless Night","Pitch Perfect","Coal Seam","Eigengrau","Twilight Gone","No Light"],
    White: ["Whiteout","Blank Canvas","Fresh Snow","Paper","Porcelain","Bright Light","Minimal","Blank Slate","Tabula Rasa","Pure White","Snow Day","First Snow","Powder","Blizzard","Frostbite","Glacier","Iceberg","Arctic","Polar","Snowblind","Eggshell","Ivory","Bone","Chalk","Milk","Cream","Vanilla","Marble","Alabaster","Pearl","Bleached","Pressed Linen","Cotton","Wool","Fog","Mist","Cloud Cover","Overcast","Cumulus","Heaven","Halo","Holy White","Ghost","Plain Paper","Empty Page","Negative","Snowfield","Salt Flats","Whitewash","High Key","Blown Out","Overexposed","Pure Light","Daylight","Noon Sun","Sun Bleached","Sea Foam","Foam","Whitecaps","Lace","Doily","Sugar","Flour","Coconut","Dove","Swan","Cotton Ball","Marshmallow","White Noise","Clean Slate","Spotless","Pristine","Untouched","Virgin Snow","White Room","Gallery White","White Cube","White Walls","Linen","Quartz","Limestone","Gypsum","Chalk Dust","Talc","White Gold","White Flag","Surrender","Off White","Soft White","Warm White","Cool White","Snow Globe","Frostwork","Clean Sheet","Minimalist","Less Is More","Bone White"],
};

/* ── Complementary pairs — keyed alphabetically "A+B" ──────────────────── */
export const PAIR_NAMES: Record<string, string[]> = {
    "Green+Red": ["Watermelon","Holly and Berry","Stop and Go","Red Light Green Light","Christmas","Yuletide","Mistletoe","Poinsettia","Strawberry Stem","Apple Orchard","Rose and Leaf","Ripe and Unripe","Traffic Light","Go or Stop","Roses Are Red","Chili and Lime","Mexican Flag","Italian Kitchen","Pepperoni Pizza","Cherry and Vine","Portugal","Wales","Christmas Sweater","Pomegranate","Radish","Tomato Vine","Beet and Greens","Santa Suit","Elf and Santa","Ho Ho Ho","Cranberry Sauce","Red Riding Hood","Forest and Flame","Brake and Accelerate","Ruby and Emerald","Boxing Day","Festive","Wreath","Sleigh Ride"],
    "Blue+Orange": ["Fire and Ice","Sunset and Sea","Blockbuster","Knicks","Mets","Bears","Broncos","Dolphins","Gators","Sunrise Surfer","Clownfish","Nemo","Goldfish Bowl","Dawn Patrol","Dusk on Water","Coral and Ocean","Lava and Glacier","Hot and Cold","Warm and Cool","Citrus and Sky","Tang and Tide","Tequila Sunrise","Marina Sunset","Harbor Lights","Cones and Cool","Burnt and Frozen","Ember and Frost","Pumpkin and Sky","Tiger and Tide","Phoenix Suns","Mango and Marine","Aperol Spritz","Beach Bonfire","Campfire Sky","Solar Flare","Deep Blue Sun","Movie Night","Complementary","Dusk","Sea and Flame"],
    "Purple+Yellow": ["Gold and Grape","Mardi Gras","Lakers","Vikings","Crown Royal","Royal Gold","Eggplant and Lemon","Iris and Sun","Crocus","Lilac and Daffodil","Bee and Bloom","Plum and Honey","Saffron and Plum","Amethyst and Topaz","King and Crown","Sour and Sweet","Purple Reign","Bruise and Banana","Goldenrod and Violet","Pansy","Sunflower at Dusk","Jazz Fest","Minnesota","Royal Treatment","Wisteria and Gold","Lavender Lemon","Tyrian and Gold","Pharaoh Gold","Velvet and Citron","Honeybee","Mustard and Mauve","Grape and Goldenrod","Regalia","Beeline","Dandelion Dusk","Twilight Gold"],
    "Green+Magenta": ["Watermelon","Cactus Flower","Dragonfruit","Lime and Fuchsia","Mint and Berry","Prickly Pear","Bougainvillea","Pink and Pine","Fern and Fuchsia","Beet Greens","Radish Top","Orchid and Leaf","Jungle Bloom","Hot Pink Hedge","Neon Garden","Cyber Cactus","Pitaya","Raspberry Vine","Pink Lady Apple","Rhubarb","Crepe Myrtle","Spring Azalea","Magenta Moss","Frog and Flamingo","Tropic Punch","Petal and Stem","Rose Bush","Highlighter Garden","Botanical Neon","Pink Lemon Lime","Cactus and Bloom","Hibiscus Hedge","Fuchsia Fern","Leaf and Petal","Garden Party","Loud Foliage"],
};

/* {x} = the artist's name. */
export const ARTIST_NAMES = ["All {x}","The {x} Room","{x}, Top to Bottom","Six of {x}","Card-Carrying {x}","{x} Marathon","Deep Cut: {x}","Heavy on {x}","Pure {x}","A Wall of {x}","{x} Only","Nothing but {x}","{x} Stan","{x} Maximalist","{x} Hoard","Full {x}","The {x} Suite","{x} on Repeat","{x} Loyalist","Six Times {x}","{x} Run","The {x} Wing","{x} Obsessed","Certified {x}","{x} Completist","House of {x}","The {x} Six","{x} Forever","{x} Era","The {x} Cabinet","{x} Devotee","Front Row {x}","{x} Superfan","The {x} Flex","{x} Deep","All In on {x}","The {x} Shelf","{x} to the Max","{x} Believer","The Whole {x}","{x} Top Shelf","{x} No Skips","{x} Diehard","{x} Vault","The {x} Files","{x} Cult","{x} Faithful","The {x} Gallery","{x} Heavy Rotation","Wall to Wall {x}"];

/* {x} = the project name. */
export const PROJECT_NAMES = ["All {x}","Deep in {x}","The {x} Wall","{x} Run","Heavy on {x}","Pure {x}","Six of {x}","{x} Only","Nothing but {x}","The {x} Set","Full {x}","{x} Stack","The {x} Six","{x} Vault","Loaded with {x}","{x} Completist","The {x} Wing","{x} Deep Cut","{x} Hoard","The {x} Block","All In on {x}","The Whole {x}","{x} Top Shelf","{x} No Skips","The {x} Shelf","{x} Believer","Six from {x}","The {x} Cabinet","{x} Heavy","The {x} Drop","Wall to Wall {x}"];

export const RANDOM_NAMES = ["Wildcard","Mixed Bag","Dealer's Choice","Salmagundi","Grab Bag","No Theme All Vibe","Scattershot","House Blend","Potluck","Variety Pack","Sampler","Tasting Menu","Mixtape","B-Sides","Odds and Ends","This and That","Bric-a-Brac","Hodgepodge","Mishmash","Smorgasbord","Pick and Mix","Assorted","Kitchen Sink","Whatever Sticks","Vibes Only","Pure Vibes","Random Access","Shuffle Play","Gallery Roulette","Eclectic","A Bit of Everything","Lucky Dip","Surprise Me","Curator Off Duty","No Notes","Free Association","Loose Curation","Anti-Theme","Themeless","Untethered","Organized Chaos","Controlled Chaos","Magpie Energy","Magpie Mode","On a Whim","Caprice","Found Objects","Wunderkammer","Cabinet of Curiosities","Curio","Miscellany","Sundry","Ragtag","Motley Crew","Motley","Patchwork","Crazy Quilt","Junk Drawer","Mood Board","Vibe Check","No Rules","Freestyle","Improv","Medley","Remix","Mashup","Crossover","Wild Mix","Anything Goes","Open Bar","Buffet","All Sorts","Catchall","Pell-Mell","Random Walk","Coin Flip","Dice Roll","Spin the Wheel","Chef's Whim","Off the Cuff","Spontaneous"];

/* ── Colour FAMILIES ───────────────────────────────────────────────────── */
export const FAMILY_NAMES = {
    warm: ["Warm Front","Heat Wave","Warm Tones","Sunbaked","Toasty","Hot Side","Fireside","Desert Heat","Embers","Spice Rack","Golden Warmth","Hearthlight","Sunburnt","Warm Spectrum","Hot Half"],
    cool: ["Cool Tones","Cool Down","Ice Box","Cold Side","Deep Freeze","Chillwave","Sub Zero","Cool Spectrum","Frostbitten","Glacial","Blue Note","Cold Half","Arctic Air","Cooling Off","Winter Set"],
    neutral: ["Neutral Territory","Quiet Tones","Greige","Earth and Bone","Beige Mode","Muted","Soft Neutrals","No Drama","Low Key","Natural Tones","Sand and Stone","Understated","Off Duty","Quiet Luxury","The Neutrals"],
    monochrome: ["Greyscale","Monochrome","Black and White","Noir et Blanc","Ink and Snow","Zebra","Tuxedo","Chiaroscuro","Newsprint","Static","Grayscale Mode","No Colour","Salt and Pepper","Piano Keys","High Contrast"],
    rainbow: ["Full Spectrum","Rainbow Order","ROYGBIV","All the Colours","Prism","Spectrum","Taste the Rainbow","Pride","Colour Wheel","Refraction","Pantone Run","Every Hue","Maximalist","Skittles","The Whole Box"],
};

/* {x}=sign. Natal sets — the sky an Output was born under. */
export const SUN_NAMES = ["{x} Suns","{x} Season","Sun in {x}","Born Under {x}","All {x}","{x} Energy","{x} Sun Club","Pure {x}","{x} Solar","Six {x} Suns"];
export const MOON_NAMES = ["{x} Moons","Moon in {x}","{x} Moon Children","Lunar {x}","{x} Tides","All {x} Moons","Night {x}","{x} Moonlight","{x} by Moon","Six {x} Moons"];
export const RISING_NAMES = ["{x} Rising","{x} Ascendant","{x} on the Horizon","Rising {x}","{x} Ascending","All {x} Rising","{x} on the Up","{x} Skyline","Dawn of {x}","Six {x} Rising"];

/* Combos. {c}=colour, {x}=artist/project. */
export const ARTIST_COLOR_NAMES = ["{x} in {c}","{c} {x}","{x}, {c} Phase","{x} Goes {c}","{x} Sees {c}","The {c} {x}","{x} on {c}","{x}, All {c}","{c} Era {x}","{x} ({c})"];
export const PROJECT_COLOR_NAMES = ["{x} in {c}","{c} {x}","{x}, {c} Cut","All {c} {x}","{x} on {c}","The {c} {x}","{x} ({c})","{c} Side of {x}"];

/* ── Colour-harmony theory ─────────────────────────────────────────────── */
/* Analogous = neighbouring hues that blend into a gradient. */
export const ANALOGOUS_NAMES = ["Ombré","Gradient","Colour Run","Analogous","Smooth Blend","Hue Run","Tonal Run","Fade","Graduated","The Blend","Soft Transition","Neighbours"];
export const ANALOGOUS_WARM_NAMES = ["Sunset","Sunset Gradient","Heat Map","Warm Fade","Fire Run","Dawn","Magic Hour","Desert Sunset","Ember Gradient","Golden Ombré"];
export const ANALOGOUS_COOL_NAMES = ["Ocean","Deep Sea","Cool Fade","Twilight","Dusk Gradient","Sea and Sky","Northern Lights","Glacier Run","Nightfall","Cool Ombré"];
/* Triadic = three hues evenly spaced on the wheel. */
export const TRIADIC_NAMES = ["Primary Colours","The Triad","Triadic","Colour Theory","Three-Way","RYB","Bauhaus","Mondrian","Three of a Kind","Tricolour"];

/* ── Astrology — same element across Sun signs ─────────────────────────── */
export const ELEMENT_NAMES = {
    Fire:  ["Fire Signs","All Fire","Born to Burn","Fire Trio","Playing with Fire","Cardinal Heat","The Fire Element"],
    Earth: ["Earth Signs","All Earth","Grounded","Salt of the Earth","The Earth Element","Down to Earth","Earthbound"],
    Air:   ["Air Signs","All Air","Heads in the Clouds","Air Apparent","The Air Element","Light as Air","Breezy"],
    Water: ["Water Signs","All Water","Deep Feelers","Water Babies","The Water Element","Still Waters","Tidal"],
};

/* ── Born on the same PriceDay (a mint cohort). {x}=the PriceDay. ───────── */
export const PRICEDAY_NAMES = ["Born on {x}","{x} Class","The {x} Cohort","Day {x} Club","Same Birthday","{x} Babies","Minted on {x}","The Class of {x}","{x} Reunion","Day {x} Crew"];

/* ── Maximum variety — one of everything ───────────────────────────────── */
export const RANGE_NAMES = ["The Range","Full Roster","No Repeats","One Each","The Spread","Variety Hour","Range Rover","Sampler Platter","All Over the Map","Breadth","The Whole Range","Diversified"];

/* ── PriceSprite as CURATOR. The buried gem: now and then the user's sprite is
   framed as having hand-picked the set, in its archetype's VOICE. {handle} = the
   profile's @name. Observer = quiet/tonal, Instigator = loud/clashing, Hacker =
   chaotic/glitchy, Mystic = cosmic — each also biases WHICH sets it picks. ── */
/* ── Fate — shared I Ching hexagram. {x}=the Fate word. ────────────────── */
export const FATE_NAMES = ["All {x}","The Sign of {x}","Marked by {x}","Under {x}","Hexagram: {x}","{x}, Six Times","Bound by {x}","Six Fates of {x}","The {x} Line","Cast as {x}"];

/* ── token_id magic ────────────────────────────────────────────────────── */
export const ANGEL_NAMES = ["Angel Numbers","Repdigits","Seeing Triples","Master Numbers","Make a Wish","Lucky Repeats","Numerology","The Same Digit","Mirror Numbers","11:11"];
export const LOWMINT_NAMES = ["Single Digits","Low Mints","Under Ten","First Editions","Early Birds","Top of the Stack","The Front Row","Low Numbers","Minted Early","The First Few"];
/* {x}=the shared number. */
export const SAMENUM_NAMES = ["The {x} Club","Lucky Number {x}","All {x}s","Number {x}","{x} Across the Board","Same Digits, Different Worlds","The {x}s","Matching {x}s"];

/* ── Market mood (listing status) ──────────────────────────────────────── */
export const LISTED_NAMES = ["Everything Must Go","On the Block","For Sale","The Sale Rack","Priced to Move","Open to Offers","Make Me an Offer","Liquidation","Yard Sale","On the Market"];
export const HELD_NAMES = ["The Vault","Not For Sale","Cold Storage","Diamond Hands","Locked Up","Keepers","Held Tight","Never Selling","The Safe","Off the Market"];

/* ── Astrology, deeper ─────────────────────────────────────────────────── */
/* {x}=sign. The rare case where Sun = Moon = Rising. */
export const TRIPLE_NAMES = ["Triple {x}","{x} Cubed","{x} to the Core","Pure {x}","All {x}, All Ways","Big Three: {x}","{x} Through and Through","Unanimously {x}"];
export const MODALITY_NAMES = {
    Cardinal: ["Cardinal Signs","Movers and Shakers","The Initiators","First Movers","Cardinal Energy"],
    Fixed: ["Fixed Signs","Set in Stone","The Stubborn Lot","Immovable","Fixed Energy"],
    Mutable: ["Mutable Signs","Shape-Shifters","Go With the Flow","The Adaptors","Mutable Energy"],
};

/* ── Aspect ratio — lights up if/when we capture it (future-proof). ─────── */
export const ASPECT_NAMES = {
    square: ["Perfect Squares","All Square","Square One","Boxed Set","The Squares","Squared Away"],
    wide: ["Widescreen","Cinemascope","The Landscapes","Wide Load","Letterbox","Panorama"],
    tall: ["Portrait Mode","The Tall Ones","Standing Tall","Vertical Hold","Skyscrapers","Upright"],
};

/* ── Social graph — by artists the owner follows (future wiring). ───────── */
export const FOLLOWING_NAMES = ["From the Feed","People I Follow","My Algorithm","The Following","Artists I Stan","Off the Timeline","My Curators","Who I Watch"];

/* ── Visual fingerprint themes (brightness / saturation / complexity) ───── */
export const DARK_NAMES = ["Into the Dark","After Dark","Night Shift","Low Light","Lights Low","Shadow Play","The Dark Set","Nocturne","Black Box","Dimmed"];
export const LIGHT_NAMES = ["Bright Lights","High Key","Daylight","Washed in Light","Lights Up","Sun's Out","The Bright Set","Luminous","Overexposed","Glow Up"];
export const VIVID_NAMES = ["Neon Dreams","Vivid","Saturated","Turn It Up","Full Colour","Loud Colour","Chroma Max","Pop Art","Technicolor","Eye Candy"];
export const MUTED_NAMES = ["Muted","Pastel Hour","Faded","Soft Focus","Dusty","Quiet Colour","Low Saturation","Washed Out","Desaturated","Whisper Tones"];
export const BUSY_NAMES = ["Busy Signal","Maximalist","A Lot Going On","Dense","Detail Overload","Visual Noise","Packed","Intricate","Wall of Detail","Information Density"];
export const MINIMAL_NAMES = ["Minimalist","Less Is More","Negative Space","Clean","Sparse","Breathing Room","Quiet Composition","Bare","Restraint","White Space"];

export const VIBE_CAPTIONS = {
    observer: ["{handle}'s Eye","Noticed These","Under Observation","The Quiet Picks","Seen and Filed","A Pattern Emerged","Nothing Loud Here","Caught in Passing","The Long Look","Six Things Worth Watching","Filed Without Comment","Tonal, As Expected","Observed and Kept","The Understated Set","Quietly Noted","Watching, Always","A Study in Restraint","Less, On Purpose","The Periphery","Held in View","Subtle by Selection","Noted, Not Announced","The Margins Speak","What Stayed Still","Collected in Silence","The Soft Inventory","Recorded, Unhurried","Six Calm Findings","The Watcher's Shortlist","Edges and Undertones","Seen From a Distance","Nothing Insists Here","The Patient Six","Catalogued Quietly","A Low Hum of Things","The Overlooked, Reconsidered","Logged at Dusk","Faint Signals","What the Room Forgot","Witnessed, Then Chosen"],
    instigator: ["{handle}'s Sprite Says Fight Me","Stirring the Pot","Loud on Purpose","No Notes, All Nerve","Picked to Provoke","Six Ways to Argue","Clash Intended","Try and Look Away","Made You Look","Six Reasons to Riot","Bold or Nothing","The Pot, Officially Stirred","Volume at Eleven","Come Get Mad","Subtle Is for Cowards","Six Slaps to the Eye","Yeah I Said It","Pick a Fight","The Chaos Slate","Unapologetically Loud","Don't @ Me","Maximum, On Brand","Six Dares","Disagree, I Dare You","All Gas, No Calm","Pure Nerve, Zero Chill","The Provocation Set","Wake the Room","Six Shots Fired","Hotter Takes","Built to Rattle","This One's a Statement","Boldface, Underlined","The Mess, Curated","Six Reasons to Stare","No Apology Issued","Walk It Off","Eyes Up, Cowards","The Loud Six","Cause a Scene"],
    hacker: ["root@{handle}","// curated","Brute-Forced","sudo show off","404 Theme Not Found","Six Files, Zero Mercy","rm -rf the Rules","git push --chaos","Glitched on Purpose","Output Stream","cat ./taste","Compiled From Noise","segfault, but Pretty","Override Accepted","Six Returns, No Errors","echo {handle}","Permission Granted","The Stack Trace","Decoded These Six","exit 0","Forked the Canon","Patched in Static","Six Packets Sniffed","Random Seed Set","grep -i beauty","Buffer Overflow","The Daemon Picked","Null but Vibing","Six Bits Flipped","Injected Taste","Recompiled the Gallery","Kernel Panic, Lovely","Pulled From /dev/random","The Glitch Stays","Six Commits, No Log","Hooked the Output","Ran It as Root","String Theory","Dump and Display","Sniffed the Packets"],
    mystic: ["{handle}'s Sprite Read the Stars","Written in the Charts","The Cards Chose These","Cosmic Pull","As the Stars Aligned","Six Drawn From Fate","The Veil Lifted Briefly","Mercury Insisted","Pulled From the Ether","The Oracle Points Here","By Moon and Marrow","Six Omens, Framed","What the Tide Whispered","Foretold, Then Found","The Threads Crossed Here","Cast in Starlight","The Chart Demanded It","Drawn From the Deep","Six Signs Converged","A Reading in Pigment","The Cosmos Curated","Fated to Be Seen","The Stars Did Insist","Whispered by the Dark","Six Fates, One Frame","The Augur's Choice","Aligned and Offered","What the Dream Returned","The Eclipse Selected","By Candle and Comet","The Threshold Set","Six Truths in Orbit","Divined, Not Decided","The Spiral Pointed Here","As Above, So Curated","The Hour Was Auspicious","Pulled by Unseen Hands","The Constellation Speaks","Six Stars, Hand-Picked","Fortune Framed These"],
};
