-- ── BRENDON'S CARDS — the home news rail's editorial slot (Brendon, 2026-07-29)
--   The rail's curated pills, previously a hardcoded empty list in the app with
--   no screen behind it. This is that store: God Mode writes, the home payload
--   reads, everyone sees the same cards.
--
--   One row = one pill on the rail: glyph · tag (top line) · title (headline)
--   · meta (detail) · href (optional link). `active` hides a card without
--   deleting it; `position` orders the set (the rail shuffles everything
--   else, but Brendon's own cards keep the order he sets).
-- Additive, non-destructive — new table only.

CREATE TABLE IF NOT EXISTS public.home_news_cards (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  glyph       text,
  tag         text NOT NULL,
  title       text NOT NULL,
  meta        text,
  href        text,
  active      boolean NOT NULL DEFAULT true,
  position    integer NOT NULL DEFAULT 0,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS home_news_cards_active_idx
  ON public.home_news_cards (active, position, id);

ALTER TABLE public.home_news_cards ENABLE ROW LEVEL SECURITY;

-- PUBLIC READ of the LIVE cards only — a card is front-page copy, and a
-- parked one stays private until it's switched on. Writes never come through
-- the anon key: the God Mode route uses the service role behind a SIWE +
-- owner-wallet check.
DROP POLICY IF EXISTS home_news_cards_read_active ON public.home_news_cards;
CREATE POLICY home_news_cards_read_active
  ON public.home_news_cards
  FOR SELECT
  TO anon, authenticated
  USING (active);

GRANT SELECT ON public.home_news_cards TO anon, authenticated;
