/*
 * lib/color/vocabulary — the Colorpedia's named-colour vocabulary.
 *
 * A FIXED, baked-in dictionary of real colour names with real hex values. It is
 * DATA, not generation: nothing here is produced at runtime, so the Colorpedia
 * cannot hallucinate a name, a number, or a story in front of a user (Brendon,
 * 2026-08-01).
 *
 * Any arbitrary colour — a hex sampled off a piece of art, a project's custom
 * colorway — snaps to its nearest neighbour in here by perceptual distance
 * (CIEDE2000). The panel always says WHICH named colour it matched and how far
 * away it is, so a snapped colour never pretends the story is its own.
 *
 * `note` carries the history, and it is only present where a colour genuinely
 * has one. A name with no note shows no note — an empty line beats an invented
 * one.
 */

export interface NamedColor {
    name: string;
    hex: string;
    /** Where the name comes from — the shelf it sits on. */
    origin: 'CSS' | 'Pigment' | 'Dye' | 'Heritage' | 'Nature' | 'Metal' | 'Modern';
    /** The colour's story. Absent when there isn't a real one to tell. */
    note?: string;
    /** Extra search terms — alternate spellings, systems, nicknames. */
    alt?: string[];
}

/* ── CSS / X11 keywords ───────────────────────────────────────────────────
   The 147 names any browser answers to. They are the one vocabulary a colour
   can be addressed by in code as well as in words, so they lead. */
const CSS_COLORS: NamedColor[] = [
    { name: 'Alice Blue', hex: '#F0F8FF', origin: 'CSS', note: 'Named for Alice Roosevelt Longworth, whose pale blue gown set a fashion craze in 1902 America. It reached the web through the X11 window system\'s colour list.' },
    { name: 'Antique White', hex: '#FAEBD7', origin: 'CSS' },
    { name: 'Aqua', hex: '#00FFFF', origin: 'CSS', alt: ['cyan'], note: 'Full green plus full blue — one of the three additive secondaries, and the C in CMYK\'s cyan. Identical to Cyan; the web kept both names.' },
    { name: 'Aquamarine', hex: '#7FFFD4', origin: 'CSS', note: 'Latin aqua marina, "sea water" — the beryl gemstone Roman sailors carried as a charm against drowning.' },
    { name: 'Azure', hex: '#F0FFFF', origin: 'CSS', note: 'From Persian lāžward, the same root that gives us lapis lazuli. The web keyword drifted far paler than the deep sky-blue the word means in heraldry.' },
    { name: 'Beige', hex: '#F5F5DC', origin: 'CSS', note: 'Originally French for undyed, unbleached wool — a colour defined by the absence of any dyer\'s work.' },
    { name: 'Bisque', hex: '#FFE4C4', origin: 'CSS' },
    { name: 'Black', hex: '#000000', origin: 'CSS', note: 'The absence of emitted light. On a screen it is a pixel switched off; in pigment it is the hardest colour to make truly neutral, which is why painters have argued over blacks for centuries.' },
    { name: 'Blanched Almond', hex: '#FFEBCD', origin: 'CSS' },
    { name: 'Blue', hex: '#0000FF', origin: 'CSS', note: 'The last of the primaries to get a name in most languages — Homer never used one, calling the sea "wine-dark" instead. Now the most-named favourite colour on earth.' },
    { name: 'Blue Violet', hex: '#8A2BE2', origin: 'CSS' },
    { name: 'Brown', hex: '#A52A2A', origin: 'CSS', note: 'Not a spectral colour at all — brown is dark orange. It only exists in context: the same light shown in isolation reads as a dim orange-red.' },
    { name: 'Burlywood', hex: '#DEB887', origin: 'CSS' },
    { name: 'Cadet Blue', hex: '#5F9EA0', origin: 'CSS' },
    { name: 'Chartreuse', hex: '#7FFF00', origin: 'CSS', note: 'Named after the green liqueur made by Carthusian monks near Grenoble since 1737 — the only colour named for a drink whose recipe is still a monastic secret.' },
    { name: 'Chocolate', hex: '#D2691E', origin: 'CSS' },
    { name: 'Coral', hex: '#FF7F50', origin: 'CSS', note: 'The colour of precious red coral, harvested in the Mediterranean since antiquity and worn as protection against the evil eye.' },
    { name: 'Cornflower Blue', hex: '#6495ED', origin: 'CSS', note: 'Centaurea cyanus, once a common weed in European grain fields and now endangered there — modern herbicides nearly finished it off.' },
    { name: 'Cornsilk', hex: '#FFF8DC', origin: 'CSS' },
    { name: 'Crimson', hex: '#DC143C', origin: 'CSS', note: 'From Arabic qirmiz, the kermes insect crushed to make the dye. Every deep red name in Europe — crimson, carmine, cramoisy — traces back to that one bug.' },
    { name: 'Cyan', hex: '#00FFFF', origin: 'CSS', alt: ['aqua'], note: 'From Greek kyanos, "dark blue". The C of CMYK: the ink that subtracts red from white paper.' },
    { name: 'Dark Blue', hex: '#00008B', origin: 'CSS' },
    { name: 'Dark Cyan', hex: '#008B8B', origin: 'CSS' },
    { name: 'Dark Goldenrod', hex: '#B8860B', origin: 'CSS' },
    { name: 'Dark Gray', hex: '#A9A9A9', origin: 'CSS', alt: ['dark grey'] },
    { name: 'Dark Green', hex: '#006400', origin: 'CSS' },
    { name: 'Dark Khaki', hex: '#BDB76B', origin: 'CSS' },
    { name: 'Dark Magenta', hex: '#8B008B', origin: 'CSS' },
    { name: 'Dark Olive Green', hex: '#556B2F', origin: 'CSS' },
    { name: 'Dark Orange', hex: '#FF8C00', origin: 'CSS' },
    { name: 'Dark Orchid', hex: '#9932CC', origin: 'CSS' },
    { name: 'Dark Red', hex: '#8B0000', origin: 'CSS' },
    { name: 'Dark Salmon', hex: '#E9967A', origin: 'CSS' },
    { name: 'Dark Sea Green', hex: '#8FBC8F', origin: 'CSS' },
    { name: 'Dark Slate Blue', hex: '#483D8B', origin: 'CSS' },
    { name: 'Dark Slate Gray', hex: '#2F4F4F', origin: 'CSS', alt: ['dark slate grey'] },
    { name: 'Dark Turquoise', hex: '#00CED1', origin: 'CSS' },
    { name: 'Dark Violet', hex: '#9400D3', origin: 'CSS' },
    { name: 'Deep Pink', hex: '#FF1493', origin: 'CSS' },
    { name: 'Deep Sky Blue', hex: '#00BFFF', origin: 'CSS' },
    { name: 'Dim Gray', hex: '#696969', origin: 'CSS', alt: ['dim grey'] },
    { name: 'Dodger Blue', hex: '#1E90FF', origin: 'CSS', note: 'Named for the Los Angeles Dodgers — one of the very few X11 colours taken from a sports team.' },
    { name: 'Firebrick', hex: '#B22222', origin: 'CSS', note: 'The colour of refractory brick used to line furnaces and kilns — iron-rich clay that has been fired until it goes deep red.' },
    { name: 'Floral White', hex: '#FFFAF0', origin: 'CSS' },
    { name: 'Forest Green', hex: '#228B22', origin: 'CSS' },
    { name: 'Fuchsia', hex: '#FF00FF', origin: 'CSS', alt: ['magenta'], note: 'Named for the fuchsia flower, itself named for the botanist Leonhart Fuchs. Identical in value to Magenta — the web kept both spellings, and the flower is regularly misspelled "fuschia".' },
    { name: 'Gainsboro', hex: '#DCDCDC', origin: 'CSS', note: 'A quiet nod to the painter Thomas Gainsborough — one of the stranger survivals in the X11 list.' },
    { name: 'Ghost White', hex: '#F8F8FF', origin: 'CSS' },
    { name: 'Gold', hex: '#FFD700', origin: 'CSS' },
    { name: 'Goldenrod', hex: '#DAA520', origin: 'CSS' },
    { name: 'Gray', hex: '#808080', origin: 'CSS', alt: ['grey'], note: 'The web\'s "gray" sits at hex 80 — the exact numeric midpoint of the byte, not the perceptual midpoint of light. Middle grey to the eye is nearer #BCBCBC.' },
    { name: 'Green', hex: '#008000', origin: 'CSS', note: 'The web keyword is HALF-strength green; full green is "Lime". A quirk inherited from the original 16 HTML colours, and a permanent trap for anyone writing CSS from memory.' },
    { name: 'Green Yellow', hex: '#ADFF2F', origin: 'CSS' },
    { name: 'Honeydew', hex: '#F0FFF0', origin: 'CSS' },
    { name: 'Hot Pink', hex: '#FF69B4', origin: 'CSS' },
    { name: 'Indian Red', hex: '#CD5C5C', origin: 'CSS', note: 'Named for the iron-oxide earth pigment mined in India, not for any people — the same red ochre humans have used since the caves.' },
    { name: 'Indigo', hex: '#4B0082', origin: 'CSS', note: 'Newton inserted indigo into the rainbow to force seven colours, matching the seven notes of the musical scale. Most people cannot pick it out of a spectrum, and the web keyword is far more violet than the dye.' },
    { name: 'Ivory', hex: '#FFFFF0', origin: 'CSS' },
    { name: 'Khaki', hex: '#F0E68C', origin: 'CSS', note: 'From Urdu khākī, "dust-coloured". British soldiers in 1840s India dyed their white uniforms with tea, mud and curry powder to stop standing out; the army made it official in 1848.' },
    { name: 'Lavender', hex: '#E6E6FA', origin: 'CSS' },
    { name: 'Lavender Blush', hex: '#FFF0F5', origin: 'CSS' },
    { name: 'Lawn Green', hex: '#7CFC00', origin: 'CSS' },
    { name: 'Lemon Chiffon', hex: '#FFFACD', origin: 'CSS' },
    { name: 'Light Blue', hex: '#ADD8E6', origin: 'CSS' },
    { name: 'Light Coral', hex: '#F08080', origin: 'CSS' },
    { name: 'Light Cyan', hex: '#E0FFFF', origin: 'CSS' },
    { name: 'Light Goldenrod Yellow', hex: '#FAFAD2', origin: 'CSS' },
    { name: 'Light Gray', hex: '#D3D3D3', origin: 'CSS', alt: ['light grey'] },
    { name: 'Light Green', hex: '#90EE90', origin: 'CSS' },
    { name: 'Light Pink', hex: '#FFB6C1', origin: 'CSS' },
    { name: 'Light Salmon', hex: '#FFA07A', origin: 'CSS' },
    { name: 'Light Sea Green', hex: '#20B2AA', origin: 'CSS' },
    { name: 'Light Sky Blue', hex: '#87CEFA', origin: 'CSS' },
    { name: 'Light Slate Gray', hex: '#778899', origin: 'CSS', alt: ['light slate grey'] },
    { name: 'Light Steel Blue', hex: '#B0C4DE', origin: 'CSS' },
    { name: 'Light Yellow', hex: '#FFFFE0', origin: 'CSS' },
    { name: 'Lime', hex: '#00FF00', origin: 'CSS', note: 'Full-strength green — the brightest colour a screen can make, and the one the eye is most sensitive to. Green gets more bits in most video codecs for exactly this reason.' },
    { name: 'Lime Green', hex: '#32CD32', origin: 'CSS' },
    { name: 'Linen', hex: '#FAF0E6', origin: 'CSS' },
    { name: 'Magenta', hex: '#FF00FF', origin: 'CSS', alt: ['fuchsia'], note: 'Named in 1859 for the Battle of Magenta, fought in Italy the same year the aniline dye was patented. It has no wavelength — the brain invents it where the spectrum wraps from red to violet.' },
    { name: 'Maroon', hex: '#800000', origin: 'CSS', note: 'From French marron, "chestnut". Like Green, the web keyword is half-strength — the original 16 HTML colours were built from a simple on/half/off grid.' },
    { name: 'Medium Aquamarine', hex: '#66CDAA', origin: 'CSS' },
    { name: 'Medium Blue', hex: '#0000CD', origin: 'CSS' },
    { name: 'Medium Orchid', hex: '#BA55D3', origin: 'CSS' },
    { name: 'Medium Purple', hex: '#9370DB', origin: 'CSS' },
    { name: 'Medium Sea Green', hex: '#3CB371', origin: 'CSS' },
    { name: 'Medium Slate Blue', hex: '#7B68EE', origin: 'CSS' },
    { name: 'Medium Spring Green', hex: '#00FA9A', origin: 'CSS' },
    { name: 'Medium Turquoise', hex: '#48D1CC', origin: 'CSS' },
    { name: 'Medium Violet Red', hex: '#C71585', origin: 'CSS' },
    { name: 'Midnight Blue', hex: '#191970', origin: 'CSS' },
    { name: 'Mint Cream', hex: '#F5FFFA', origin: 'CSS' },
    { name: 'Misty Rose', hex: '#FFE4E1', origin: 'CSS' },
    { name: 'Moccasin', hex: '#FFE4B5', origin: 'CSS' },
    { name: 'Navajo White', hex: '#FFDEAD', origin: 'CSS' },
    { name: 'Navy', hex: '#000080', origin: 'CSS', note: 'The Royal Navy standardised on dark blue uniforms in 1748 — the colour was cheap, hid dirt, and held its dye at sea. Every navy since copied it.' },
    { name: 'Old Lace', hex: '#FDF5E6', origin: 'CSS' },
    { name: 'Olive', hex: '#808000', origin: 'CSS' },
    { name: 'Olive Drab', hex: '#6B8E23', origin: 'CSS', note: 'The US Army\'s field colour from 1902 through Vietnam — chosen because it disappeared into more landscapes than anything else tested.' },
    { name: 'Orange', hex: '#FFA500', origin: 'CSS', note: 'English had no word for it until the fruit arrived — before that the colour was "yellow-red". The fruit named the colour, never the other way round.' },
    { name: 'Orange Red', hex: '#FF4500', origin: 'CSS' },
    { name: 'Orchid', hex: '#DA70D6', origin: 'CSS' },
    { name: 'Pale Goldenrod', hex: '#EEE8AA', origin: 'CSS' },
    { name: 'Pale Green', hex: '#98FB98', origin: 'CSS' },
    { name: 'Pale Turquoise', hex: '#AFEEEE', origin: 'CSS' },
    { name: 'Pale Violet Red', hex: '#DB7093', origin: 'CSS' },
    { name: 'Papaya Whip', hex: '#FFEFD5', origin: 'CSS' },
    { name: 'Peach Puff', hex: '#FFDAB9', origin: 'CSS' },
    { name: 'Peru', hex: '#CD853F', origin: 'CSS' },
    { name: 'Pink', hex: '#FFC0CB', origin: 'CSS', note: 'Named for the flower (pinks — Dianthus), whose frilled petals look cut with pinking shears. The gendered pink/blue split for babies is a 20th-century invention; before the 1940s pink was often the boy\'s colour, as a lighter red.' },
    { name: 'Plum', hex: '#DDA0DD', origin: 'CSS' },
    { name: 'Powder Blue', hex: '#B0E0E6', origin: 'CSS' },
    { name: 'Purple', hex: '#800080', origin: 'CSS', note: 'For 1,500 years purple meant Tyrian purple, a dye so costly Roman law restricted it to emperors. The web keyword is a half-strength red-blue mix that costs nothing.' },
    { name: 'Rebecca Purple', hex: '#663399', origin: 'CSS', note: 'Added to CSS in 2014 in memory of Rebecca Meyer, the six-year-old daughter of web standards author Eric Meyer. Purple was her favourite colour. It is the only CSS keyword adopted as a memorial.' },
    { name: 'Red', hex: '#FF0000', origin: 'CSS', note: 'The first colour every language names after black and white, without exception. Red ochre is the oldest pigment humans used — 300,000 years and counting.' },
    { name: 'Rosy Brown', hex: '#BC8F8F', origin: 'CSS' },
    { name: 'Royal Blue', hex: '#4169E1', origin: 'CSS', note: 'Said to have been mixed by Rachel Baynes\' mill in Somerset to win a competition set by George III for a dress blue fit for the queen.' },
    { name: 'Saddle Brown', hex: '#8B4513', origin: 'CSS' },
    { name: 'Salmon', hex: '#FA8072', origin: 'CSS' },
    { name: 'Sandy Brown', hex: '#F4A460', origin: 'CSS' },
    { name: 'Sea Green', hex: '#2E8B57', origin: 'CSS' },
    { name: 'Seashell', hex: '#FFF5EE', origin: 'CSS' },
    { name: 'Sienna', hex: '#A0522D', origin: 'CSS', note: 'Terra di Siena — the iron-rich earth dug near Siena in Tuscany. Roasting it drives off water and turns it redder, which is the difference between raw and burnt sienna.' },
    { name: 'Silver', hex: '#C0C0C0', origin: 'CSS' },
    { name: 'Sky Blue', hex: '#87CEEB', origin: 'CSS', note: 'The sky is blue because air scatters short wavelengths far more than long ones — Rayleigh scattering. It is the only colour in this list you cannot point at.' },
    { name: 'Slate Blue', hex: '#6A5ACD', origin: 'CSS' },
    { name: 'Slate Gray', hex: '#708090', origin: 'CSS', alt: ['slate grey'] },
    { name: 'Snow', hex: '#FFFAFA', origin: 'CSS' },
    { name: 'Spring Green', hex: '#00FF7F', origin: 'CSS' },
    { name: 'Steel Blue', hex: '#4682B4', origin: 'CSS' },
    { name: 'Tan', hex: '#D2B48C', origin: 'CSS', note: 'From tannum, oak bark — the agent that turns raw hide into leather and stains it this colour in the process.' },
    { name: 'Teal', hex: '#008080', origin: 'CSS', note: 'Named for the stripe on a teal duck\'s head. It became the defining colour of early-90s design partly because it looked good on the limited palettes of the era.' },
    { name: 'Thistle', hex: '#D8BFD8', origin: 'CSS' },
    { name: 'Tomato', hex: '#FF6347', origin: 'CSS' },
    { name: 'Turquoise', hex: '#40E0D0', origin: 'CSS', note: 'French for "Turkish stone" — the mineral reached Europe through Turkey, though it was mined in Persia and the Sinai.' },
    { name: 'Violet', hex: '#EE82EE', origin: 'CSS', note: 'The only "purple" that is a real spectral colour, sitting at the short-wavelength end of visible light. Everything else in the purple family is a mix the brain assembles.' },
    { name: 'Wheat', hex: '#F5DEB3', origin: 'CSS' },
    { name: 'White', hex: '#FFFFFF', origin: 'CSS', note: 'Every emitter at full. On a screen white is three lights lying convincingly; on paper it is the absence of ink and the presence of a brightener.' },
    { name: 'White Smoke', hex: '#F5F5F5', origin: 'CSS' },
    { name: 'Yellow', hex: '#FFFF00', origin: 'CSS', note: 'The brightest hue at full saturation, which is why it is the world\'s default warning colour — and why it is nearly unreadable as text on white.' },
    { name: 'Yellow Green', hex: '#9ACD32', origin: 'CSS' },
];

/* ── Pigments — the colours you can hold in your hand ────────────────────
   Where colour history actually happened: what could be ground, burnt, mined
   or precipitated set the limits of every painting ever made. */
const PIGMENTS: NamedColor[] = [
    { name: 'Vermilion', hex: '#E34234', origin: 'Pigment', note: 'Ground cinnabar — mercury sulphide. Brilliant, expensive and poisonous; it also blackens on exposure to light, which is why some medieval reds have gone dark. Chinese alchemists learned to make it synthetically over a thousand years before Europe did.' },
    { name: 'Cinnabar', hex: '#E44D2E', origin: 'Pigment', note: 'The mineral vermilion is ground from. Roman mines at Almadén in Spain were worked by slaves and convicts — the life expectancy in a cinnabar mine was measured in years.' },
    { name: 'Ultramarine', hex: '#120A8F', origin: 'Pigment', note: 'Ground lapis lazuli, hauled from one valley in Afghanistan. Latin ultramarinus — "beyond the sea". It cost more than gold, so contracts specified how much of it a painter had to use on the Virgin\'s robe. A synthetic version arrived in 1826 and destroyed the price overnight.' },
    { name: 'Prussian Blue', hex: '#003153', origin: 'Pigment', note: 'The first modern synthetic pigment, made by accident in Berlin around 1706 when a colourmaker used potash contaminated with animal blood. It gave Hokusai\'s Great Wave its blue and is still used medically to treat heavy-metal poisoning.' },
    { name: 'Cobalt Blue', hex: '#0047AB', origin: 'Pigment', note: 'Isolated in 1802 by Thénard. The name comes from kobold, the German mine goblin blamed by miners for the ore that poisoned them and yielded no metal — it was arsenic-bearing cobalt.' },
    { name: 'Cerulean', hex: '#2A52BE', origin: 'Pigment', note: 'From Latin caelum, "sky". A cobalt stannate pigment prized because it holds its hue under artificial light better than most blues.' },
    { name: 'Egyptian Blue', hex: '#1034A6', origin: 'Pigment', note: 'The oldest known synthetic pigment — calcium copper silicate, fired around 3,200 BC. It glows in the near-infrared under red light, which archaeologists now use to find traces invisible to the eye.' },
    { name: 'Han Purple', hex: '#5218FA', origin: 'Pigment', note: 'A barium copper silicate made in China from around 800 BC and used on the Terracotta Army. Chemically it does something almost nothing else does: cooled and put in a magnetic field, it drops from three dimensions to two.' },
    { name: 'Maya Blue', hex: '#73C2FB', origin: 'Pigment', note: 'Indigo bonded into palygorskite clay by Mesoamerican makers. The result survived centuries of jungle humidity that destroyed every other organic colour — chemists only worked out how in the 1960s.' },
    { name: 'Phthalo Blue', hex: '#000F89', origin: 'Pigment', note: 'Copper phthalocyanine, found in 1927 at a Scottish dye works as a blue contaminant in a failed batch. Enormously strong — a trace tints a whole mix — and effectively permanent.' },
    { name: 'Phthalo Green', hex: '#123524', origin: 'Pigment', note: 'Phthalo blue with chlorine substituted into the ring. The same accident, one atom over.' },
    { name: 'Viridian', hex: '#40826D', origin: 'Pigment', note: 'Hydrated chromium oxide, patented in 1859 — the first green that was both brilliant and non-toxic, arriving just as painters were dying from the arsenic ones.' },
    { name: 'Scheele\'s Green', hex: '#478430', origin: 'Pigment', note: 'Copper arsenite, invented 1775 and used in everything from wallpaper to sweets. Damp rooms turned it into arsenic vapour; it is a leading suspect in Napoleon\'s death on damp St Helena, where his wallpaper was green.' },
    { name: 'Paris Green', hex: '#50C878', origin: 'Pigment', alt: ['emerald green'], note: 'Scheele\'s successor — brighter, and just as arsenical. Sold simultaneously as an artist\'s colour and as a rat poison for the Paris sewers, which is where the name came from.' },
    { name: 'Verdigris', hex: '#43B3AE', origin: 'Pigment', note: 'Copper corroded with vinegar. Unstable in oil and prone to turning brown, but for centuries it was the only strong green available — which is why so many old paintings have muddy foliage.' },
    { name: 'Malachite', hex: '#0BDA51', origin: 'Pigment', note: 'A copper carbonate mineral ground straight into pigment. Grind it fine and it goes pale; the coarser the grain, the deeper the green — the one pigment where particle size IS the colour.' },
    { name: 'Terre Verte', hex: '#6E7F63', origin: 'Pigment', alt: ['green earth'], note: 'A weak, cool green earth used as the underpainting for skin in Italian panel paintings. Where the pink glaze above it has worn away, the faces look green — Duccio\'s and Cimabue\'s figures are famous for it.' },
    { name: 'Hooker\'s Green', hex: '#49796B', origin: 'Pigment', note: 'Mixed by botanical illustrator William Hooker to match real leaves, which no single pigment did.' },
    { name: 'Indian Yellow', hex: '#E3A857', origin: 'Pigment', note: 'Imported from Bengal as foul-smelling lumps. The long-repeated story is that it was made from the urine of cows fed only mango leaves; the evidence is thin and contested, and the pigment vanished from trade around 1908 either way.' },
    { name: 'Naples Yellow', hex: '#FADA5E', origin: 'Pigment', note: 'Lead antimonate, found on Babylonian tiles and later dug from the slopes of Vesuvius. Toxic, opaque and beloved for skin tones.' },
    { name: 'Chrome Yellow', hex: '#FFA700', origin: 'Pigment', note: 'Lead chromate, 1809. Van Gogh\'s sunflowers are painted in it — and they are browning, because the pigment reduces under UV. The flowers are literally still changing colour.' },
    { name: 'Cadmium Yellow', hex: '#FFF600', origin: 'Pigment', note: 'Cadmium sulphide, from 1840. Opaque, permanent, expensive, and periodically threatened with regulation for its toxicity.' },
    { name: 'Cadmium Orange', hex: '#ED872D', origin: 'Pigment' },
    { name: 'Cadmium Red', hex: '#E30022', origin: 'Pigment', note: 'Cadmium selenide, 1910 — the pigment that finally replaced poisonous vermilion with something merely expensive.' },
    { name: 'Orpiment', hex: '#F5C71A', origin: 'Pigment', note: 'Arsenic sulphide — Latin auripigmentum, "gold pigment". Alchemists chased it believing it held real gold. It is one of the deadliest pigments ever used and it reacts with lead and copper colours, blackening its neighbours.' },
    { name: 'Gamboge', hex: '#E49B0F', origin: 'Pigment', note: 'A resin tapped from Southeast Asian trees, named after Cambodia. Also a violent purgative — Victorian watercolourists were warned not to lick the brush.' },
    { name: 'Yellow Ochre', hex: '#CC7722', origin: 'Pigment', note: 'Iron oxide clay, the oldest pigment family in the world. Ochre handprints in caves are 40,000 years old; the same earth is still sold in tubes today.' },
    { name: 'Raw Sienna', hex: '#D68A59', origin: 'Pigment' },
    { name: 'Burnt Sienna', hex: '#E97451', origin: 'Pigment', note: 'Sienna earth roasted until the yellow iron oxide converts to red. The whole "burnt" family is just the raw earth put in a furnace.' },
    { name: 'Raw Umber', hex: '#826644', origin: 'Pigment', note: 'An iron oxide earth with manganese, named for Umbria. The manganese makes it dry oil paint faster than any other pigment, which is why it turns up in underpainting.' },
    { name: 'Burnt Umber', hex: '#8A3324', origin: 'Pigment' },
    { name: 'Van Dyke Brown', hex: '#664228', origin: 'Pigment', note: 'Made from peat and lignite — literally soil. It fades badly and cracks whatever sits above it, which has quietly wrecked a great many 17th-century paintings.' },
    { name: 'Mummy Brown', hex: '#824B35', origin: 'Pigment', note: 'A bitumen brown ground from actual Egyptian mummies, human and feline, and sold into the 20th century. The Pre-Raphaelite Edward Burne-Jones buried his tube in the garden when he found out what was in it.' },
    { name: 'Sepia', hex: '#704214', origin: 'Pigment', note: 'The ink sac of the cuttlefish, genus Sepia. Used for writing since antiquity and adopted as a photographic toner because it resists fading better than plain silver.' },
    { name: 'Bistre', hex: '#3D2B1F', origin: 'Pigment', note: 'Soot from burnt beechwood, boiled and washed. Rembrandt drew in it.' },
    { name: 'Lamp Black', hex: '#1B1B1B', origin: 'Pigment', note: 'Pure carbon collected from an oil lamp\'s soot — the oldest manufactured pigment, made the same way in ancient China, Egypt and Rome. It reads slightly blue.' },
    { name: 'Ivory Black', hex: '#231F20', origin: 'Pigment', note: 'Charred bone. Once genuinely made from ivory, now from animal bone and still called bone black in industry. It reads warmer than lamp black.' },
    { name: 'Mars Black', hex: '#202020', origin: 'Pigment', note: 'Synthetic iron oxide. The "Mars" family — black, red, yellow, violet — are all lab-made iron colours named for the god of iron and war.' },
    { name: 'Payne\'s Grey', hex: '#536878', origin: 'Pigment', note: 'Mixed by watercolourist William Payne around 1800 as an alternative to black for shadows. Almost every watercolourist since has used it and quietly felt slightly guilty about it.' },
    { name: 'Davy\'s Grey', hex: '#555555', origin: 'Pigment', note: 'Powdered slate. A grey with grit in it.' },
    { name: 'Lead White', hex: '#F8F6F0', origin: 'Pigment', note: 'Made by stacking lead sheets over vinegar and dung for months. It is warm, dense and buttery, and no modern white handles like it — which is why restorers can date a painting by its white. It also poisoned generations of makers and wearers.' },
    { name: 'Titanium White', hex: '#F7F7F0', origin: 'Pigment', note: 'Titanium dioxide, commercialised in the 1920s. The most opaque white ever made, now in everything from paint to sunscreen to the coating on pills.' },
    { name: 'Zinc White', hex: '#FDFDF6', origin: 'Pigment', note: 'Cooler and more transparent than lead white, and non-toxic — the reason it took over in the 19th century. It also cracks over time, a problem restorers meet constantly.' },
    { name: 'Alizarin Crimson', hex: '#E32636', origin: 'Pigment', note: 'The colouring principle of madder root, synthesised in 1868 — the first natural dye ever made in a lab. That single result collapsed the European madder-farming industry within a decade.' },
    { name: 'Rose Madder', hex: '#E3256B', origin: 'Pigment', note: 'A lake pigment from madder root, grown around Avignon and Holland. Transparent, glowing, and notoriously fugitive in thin washes.' },
    { name: 'Carmine', hex: '#960018', origin: 'Pigment', note: 'Made from cochineal insects farmed on cactus in Oaxaca. Spain guarded the source for 250 years and got rich on it — for a time it was the New World\'s second most valuable export after silver. It is still in your food, labelled E120.' },
    { name: 'Quinacridone Magenta', hex: '#8E3A59', origin: 'Pigment', note: 'A 1950s industrial pigment class first developed for car paint, then adopted by artists for its transparency and near-total lightfastness.' },
    { name: 'Dioxazine Purple', hex: '#4A2545', origin: 'Pigment', note: 'Ferociously strong — a speck tints a whole pool of white. Modern painters mostly use it a drop at a time.' },
    { name: 'Smalt', hex: '#003399', origin: 'Pigment', note: 'Cobalt glass, ground to powder. Grind it fine enough to spread and it loses its colour, so painters had to use it coarse and gritty. It also fades to grey in oil — a great many "grey" skies in old paintings were once blue.' },
    { name: 'Azurite', hex: '#2E5894', origin: 'Pigment', note: 'The affordable blue before synthetic ultramarine. It converts to green malachite over centuries in humid air, which is why some medieval skies have quietly turned into fields.' },
    { name: 'Lapis Lazuli', hex: '#26619C', origin: 'Pigment', note: 'The stone itself — mined in Badakhshan, Afghanistan, from the same pits for over 6,000 years.' },
];

/* ── Dyes — colour on cloth, and the industry it built ───────────────── */
const DYES: NamedColor[] = [
    { name: 'Tyrian Purple', hex: '#66023C', origin: 'Dye', alt: ['imperial purple', 'royal purple'], note: 'Extracted from the murex sea snail — roughly 250,000 snails for one ounce of dye. Phoenician Tyre stank of rotting shellfish for a thousand years. Roman law made wearing it a capital offence for anyone but the emperor, and it famously deepened rather than faded with light and age.' },
    { name: 'Indigo Dye', hex: '#00416A', origin: 'Dye', note: 'The blue of every pair of jeans. Insoluble until reduced in a fermenting vat, it goes onto cloth yellow-green and turns blue in the air as you watch. That reaction is why indigo cannot be printed flat and why denim fades at the creases.' },
    { name: 'Woad', hex: '#4E6E81', origin: 'Dye', note: 'Europe\'s own indigo plant, weaker but local. Woad-growing towns like Toulouse fought imported indigo through law for two centuries, having it banned as "the devil\'s dye" before losing anyway.' },
    { name: 'Mauveine', hex: '#915F6D', origin: 'Dye', alt: ['perkin\'s mauve'], note: 'The first synthetic organic dye, made by 18-year-old William Perkin in 1856 while failing to synthesise quinine. He patented it, got rich, and started the entire modern chemical industry by accident.' },
    { name: 'Mauve', hex: '#E0B0FF', origin: 'Dye', note: 'French for the mallow flower. Perkin\'s dye made it briefly universal — the 1890s are still called the Mauve Decade.' },
    { name: 'Saffron', hex: '#F4C430', origin: 'Dye', note: 'The stigmas of Crocus sativus, three per flower, all picked by hand — around 150,000 flowers for a kilo. Still the most expensive spice on earth by weight, and a dye only the rich ever wore.' },
    { name: 'Turmeric', hex: '#E1AD21', origin: 'Dye', note: 'A brilliant, cheap yellow that fades fast in sunlight — which is why it dyes food and robes rather than anything meant to last.' },
    { name: 'Henna', hex: '#A6553A', origin: 'Dye', note: 'Lawsonia leaves, used on skin, hair and nails for at least 5,000 years across North Africa, the Middle East and South Asia. It binds to keratin, which is why it stains you and not your shirt.' },
    { name: 'Kermes', hex: '#A0002A', origin: 'Dye', note: 'The scale insect behind every European red before cochineal arrived. Its Arabic name, qirmiz, is the root of crimson.' },
    { name: 'Logwood', hex: '#3B2F4A', origin: 'Dye', note: 'A Central American heartwood that gave the first reliable cheap black. Britain and Spain fought over the logwood coast of Belize for a century.' },
    { name: 'Cochineal', hex: '#9E1B32', origin: 'Dye', note: 'The insect itself — 70,000 bodies to the pound. British redcoats, Catholic cardinals and the Mona Lisa\'s cushions all owe their red to it.' },
];

/* ── Heritage — colours a place, an institution or a person made ─────── */
const HERITAGE: NamedColor[] = [
    { name: 'International Klein Blue', hex: '#002FA7', origin: 'Heritage', alt: ['ikb', 'yves klein blue'], note: 'Yves Klein spent years finding a binder that let raw ultramarine keep its powdery intensity instead of dulling in oil. He registered the formula in 1960 and painted almost nothing else for the rest of his short life.' },
    { name: 'Baker-Miller Pink', hex: '#FF91AF', origin: 'Heritage', alt: ['drunk tank pink'], note: 'Painted on holding cells at a Seattle naval facility in 1979 after research claimed it sapped aggression. The effect never replicated properly, but prisons kept painting cells pink for years.' },
    { name: 'Falu Red', hex: '#801818', origin: 'Heritage', note: 'The red of Swedish cottages — a by-product of the Falun copper mine, cheap enough that everyone used it and protective enough that everyone kept using it. It is now a national visual signature by pure economic accident.' },
    { name: 'Barn Red', hex: '#7C0A02', origin: 'Heritage', note: 'American farmers sealed barns with linseed oil mixed with rust, which killed fungus and happened to be red. The colour came free with the preservative.' },
    { name: 'British Racing Green', hex: '#004225', origin: 'Heritage', note: 'Assigned to Britain in the pre-war international motor racing colour code — Italy got red, France blue, Germany silver. Nobody chose these for looks; they were national identifiers before sponsors existed.' },
    { name: 'Oxford Blue', hex: '#002147', origin: 'Heritage' },
    { name: 'Cambridge Blue', hex: '#A3C1AD', origin: 'Heritage' },
    { name: 'Yale Blue', hex: '#00356B', origin: 'Heritage' },
    { name: 'Carolina Blue', hex: '#4B9CD3', origin: 'Heritage' },
    { name: 'Byzantium', hex: '#702963', origin: 'Heritage' },
    { name: 'Imperial Purple', hex: '#602F6B', origin: 'Heritage' },
    { name: 'Burgundy', hex: '#800020', origin: 'Heritage' },
    { name: 'Claret', hex: '#7F1734', origin: 'Heritage', note: 'The English name for red Bordeaux, from French clairet — a lighter wine than the modern one. England drank it by the shipload while it owned Aquitaine.' },
    { name: 'Oxblood', hex: '#4A0000', origin: 'Heritage' },
    { name: 'Sangria', hex: '#92000A', origin: 'Heritage' },
    { name: 'Merlot', hex: '#73343A', origin: 'Heritage' },
    { name: 'Feldgrau', hex: '#4D5D53', origin: 'Heritage', note: 'German "field grey", adopted in 1907 — the first mass-issue uniform colour designed for the range of smokeless rifles rather than for parade.' },
    { name: 'Gunmetal', hex: '#2A3439', origin: 'Heritage' },
    { name: 'Charcoal', hex: '#36454F', origin: 'Heritage' },
    { name: 'Isabelline', hex: '#F4F0EC', origin: 'Heritage', note: 'A pale yellowish white, attached to a legend that Isabella of Spain vowed not to change her linen until a siege ended. The siege reportedly ran three years. The story is almost certainly invented; the colour name stuck anyway.' },
    { name: 'Eminence', hex: '#6C3082', origin: 'Heritage' },
    { name: 'Wenge', hex: '#645452', origin: 'Heritage' },
    { name: 'Amaranth', hex: '#E52B50', origin: 'Heritage', note: 'Greek amarantos, "unfading" — the flower that supposedly never wilts. Used since antiquity as a symbol of immortality.' },
    { name: 'Bittersweet', hex: '#FE6F5E', origin: 'Heritage' },
    { name: 'Persian Blue', hex: '#1C39BB', origin: 'Heritage' },
    { name: 'Delft Blue', hex: '#1F305E', origin: 'Heritage', note: 'Dutch potters spent the 1600s imitating imported Chinese porcelain they could not chemically reproduce, and invented a European classic while failing.' },
    { name: 'Wedgwood Blue', hex: '#6699CC', origin: 'Heritage' },
    { name: 'Tiffany Blue', hex: '#0ABAB5', origin: 'Heritage', note: 'Chosen for the first Tiffany catalogue in 1845 and now legally protected as a trademark — a colour a company owns as identity, not as ink.' },
    { name: 'Shocking Pink', hex: '#FC0FC0', origin: 'Heritage', alt: ['schiaparelli pink'], note: 'Elsa Schiaparelli launched it in 1937 and called it "life-giving, like all the light and the birds and the fish in the world put together". It was designed to be too much.' },
    { name: 'Barbie Pink', hex: '#DA1884', origin: 'Heritage' },
    { name: 'Millennial Pink', hex: '#F3CFC6', origin: 'Heritage' },
    { name: 'Safety Orange', hex: '#FF6700', origin: 'Heritage', note: 'Specified by US federal standard for maximum visibility against almost every natural background. It is the one colour chosen purely so you cannot fail to see it.' },
    { name: 'Safety Yellow', hex: '#EED202', origin: 'Heritage' },
    { name: 'Chroma Key Green', hex: '#00B140', origin: 'Modern', note: 'Green screens are green because human skin has almost no green in it, and because digital sensors carry more green pixels than red or blue — so the key cuts cleanest there.' },
];

/* ── Nature — stones, plants, weather, animals ───────────────────────── */
const NATURE: NamedColor[] = [
    { name: 'Emerald', hex: '#50C878', origin: 'Nature' },
    { name: 'Jade', hex: '#00A86B', origin: 'Nature' },
    { name: 'Peridot', hex: '#B4C424', origin: 'Nature' },
    { name: 'Citrine', hex: '#E4D00A', origin: 'Nature' },
    { name: 'Amethyst', hex: '#9966CC', origin: 'Nature', note: 'Greek amethystos, "not drunk" — the Greeks carved wine cups from it believing it prevented intoxication.' },
    { name: 'Sapphire', hex: '#0F52BA', origin: 'Nature' },
    { name: 'Ruby', hex: '#9B111E', origin: 'Nature' },
    { name: 'Garnet', hex: '#733635', origin: 'Nature' },
    { name: 'Topaz', hex: '#FFC87C', origin: 'Nature' },
    { name: 'Onyx', hex: '#353839', origin: 'Nature' },
    { name: 'Obsidian', hex: '#0B1215', origin: 'Nature' },
    { name: 'Jet', hex: '#343434', origin: 'Nature', note: 'Fossilised wood, mined at Whitby. Queen Victoria wore it in mourning for Albert and made an entire town\'s industry for forty years.' },
    { name: 'Pearl', hex: '#EAE0C8', origin: 'Nature' },
    { name: 'Coral Pink', hex: '#F88379', origin: 'Nature' },
    { name: 'Seafoam', hex: '#93E9BE', origin: 'Nature' },
    { name: 'Celadon', hex: '#ACE1AF', origin: 'Nature', note: 'The pale green glaze of Song-dynasty stoneware, so prized that Chinese courts claimed cups of it would crack if poison were poured in.' },
    { name: 'Sage', hex: '#BCB88A', origin: 'Nature' },
    { name: 'Moss Green', hex: '#8A9A5B', origin: 'Nature' },
    { name: 'Fern Green', hex: '#4F7942', origin: 'Nature' },
    { name: 'Pine Green', hex: '#01796F', origin: 'Nature' },
    { name: 'Hunter Green', hex: '#355E3B', origin: 'Nature' },
    { name: 'Bottle Green', hex: '#006A4E', origin: 'Nature' },
    { name: 'Kelly Green', hex: '#4CBB17', origin: 'Nature' },
    { name: 'Shamrock', hex: '#009E60', origin: 'Nature' },
    { name: 'Avocado', hex: '#568203', origin: 'Nature' },
    { name: 'Pistachio', hex: '#93C572', origin: 'Nature' },
    { name: 'Asparagus', hex: '#87A96B', origin: 'Nature' },
    { name: 'Artichoke', hex: '#8F9779', origin: 'Nature' },
    { name: 'Laurel Green', hex: '#A9BA9D', origin: 'Nature' },
    { name: 'Mint', hex: '#3EB489', origin: 'Nature' },
    { name: 'Eucalyptus', hex: '#44D7A8', origin: 'Nature' },
    { name: 'Pear', hex: '#D1E231', origin: 'Nature' },
    { name: 'Olive Green', hex: '#708238', origin: 'Nature' },
    { name: 'Army Green', hex: '#4B5320', origin: 'Nature' },
    { name: 'Sacramento Green', hex: '#043927', origin: 'Nature' },
    { name: 'Robin Egg Blue', hex: '#00CCCC', origin: 'Nature', note: 'Thrushes lay blue eggs because biliverdin, a pigment from broken-down blood, gets deposited in the shell — possibly to shield the embryo from UV.' },
    { name: 'Peacock', hex: '#326872', origin: 'Nature', note: 'A peacock\'s feather holds no blue pigment at all. The colour is structural — microscopic lattices interfering with light. Grind the feather up and the blue disappears.' },
    { name: 'Bondi Blue', hex: '#0095B6', origin: 'Nature' },
    { name: 'Electric Blue', hex: '#7DF9FF', origin: 'Nature' },
    { name: 'Baby Blue', hex: '#89CFF0', origin: 'Nature' },
    { name: 'Air Force Blue', hex: '#5D8AA8', origin: 'Heritage' },
    { name: 'Denim', hex: '#1560BD', origin: 'Heritage', note: 'Serge de Nîmes — cloth from Nîmes, France, shortened to denim. The weave puts indigo warp over undyed weft, which is why the inside of your jeans is white and the outside fades.' },
    { name: 'Periwinkle', hex: '#CCCCFF', origin: 'Nature' },
    { name: 'Iris', hex: '#5A4FCF', origin: 'Nature' },
    { name: 'Wisteria', hex: '#C9A0DC', origin: 'Nature' },
    { name: 'Lilac', hex: '#C8A2C8', origin: 'Nature' },
    { name: 'Heliotrope', hex: '#DF73FF', origin: 'Nature', note: 'Greek for "turns toward the sun" — the flower tracks it across the sky.' },
    { name: 'Cerise', hex: '#DE3163', origin: 'Nature' },
    { name: 'Rose', hex: '#FF007F', origin: 'Nature' },
    { name: 'Blush', hex: '#DE5D83', origin: 'Nature' },
    { name: 'Bubblegum', hex: '#FFC1CC', origin: 'Modern', note: 'Bubble gum is pink because the inventor, Walter Diemer, only had pink dye on the shelf the day it worked in 1928. Every brand since has copied the accident.' },
    { name: 'Peach', hex: '#FFE5B4', origin: 'Nature' },
    { name: 'Apricot', hex: '#FBCEB1', origin: 'Nature' },
    { name: 'Melon', hex: '#FDBCB4', origin: 'Nature' },
    { name: 'Tangerine', hex: '#F28500', origin: 'Nature' },
    { name: 'Persimmon', hex: '#EC5800', origin: 'Nature' },
    { name: 'Pumpkin', hex: '#FF7518', origin: 'Nature' },
    { name: 'Carrot', hex: '#ED9121', origin: 'Nature', note: 'Carrots were purple, white and yellow for most of their history. The orange one was bred later in the Netherlands and simply out-competed the rest.' },
    { name: 'Amber', hex: '#FFBF00', origin: 'Nature', note: 'Fossil tree resin. The Greeks called it elektron because rubbing it attracts dust — which is the root of the word electricity.' },
    { name: 'Honey', hex: '#E4A72C', origin: 'Nature' },
    { name: 'Marigold', hex: '#EAA221', origin: 'Nature' },
    { name: 'Mustard', hex: '#FFDB58', origin: 'Nature' },
    { name: 'Dijon', hex: '#C49102', origin: 'Nature' },
    { name: 'Lemon', hex: '#FFF700', origin: 'Nature' },
    { name: 'Canary', hex: '#FFFF99', origin: 'Nature' },
    { name: 'Corn', hex: '#FBEC5D', origin: 'Nature' },
    { name: 'Flax', hex: '#EEDC82', origin: 'Nature' },
    { name: 'Straw', hex: '#E4D96F', origin: 'Nature' },
    { name: 'Sunflower', hex: '#FFC512', origin: 'Nature' },
    { name: 'Daffodil', hex: '#FFFF31', origin: 'Nature' },
    { name: 'Banana', hex: '#FFE135', origin: 'Nature' },
    { name: 'Mango', hex: '#FDBE02', origin: 'Nature' },
    { name: 'Terracotta', hex: '#E2725B', origin: 'Nature', note: 'Italian for "baked earth" — the colour of any iron-bearing clay that has been fired, which is most clay, in most places, for most of human history.' },
    { name: 'Rust', hex: '#B7410E', origin: 'Nature' },
    { name: 'Desert Sand', hex: '#EDC9AF', origin: 'Nature' },
    { name: 'Sand Dune', hex: '#967117', origin: 'Nature' },
    { name: 'Camel', hex: '#C19A6B', origin: 'Nature' },
    { name: 'Fawn', hex: '#E5AA70', origin: 'Nature' },
    { name: 'Taupe', hex: '#483C32', origin: 'Nature', note: 'French for "mole" — the animal, not the mark.' },
    { name: 'Ecru', hex: '#C2B280', origin: 'Nature' },
    { name: 'Buff', hex: '#F0DC82', origin: 'Nature', note: 'The pale leather of buffalo hide, worn as military coats. "In the buff" means the same colour as the coat: bare skin.' },
    { name: 'Champagne', hex: '#F7E7CE', origin: 'Nature' },
    { name: 'Vanilla', hex: '#F3E5AB', origin: 'Nature' },
    { name: 'Cream', hex: '#FFFDD0', origin: 'Nature' },
    { name: 'Eggshell', hex: '#F0EAD6', origin: 'Nature' },
    { name: 'Bone', hex: '#E3DAC9', origin: 'Nature' },
    { name: 'Alabaster', hex: '#EDEAE0', origin: 'Nature' },
    { name: 'Ash Grey', hex: '#B2BEB5', origin: 'Nature', alt: ['ash gray'] },
    { name: 'Ebony', hex: '#555D50', origin: 'Nature' },
];

/* ── Metals ──────────────────────────────────────────────────────────── */
const METALS: NamedColor[] = [
    { name: 'Gold Metallic', hex: '#D4AF37', origin: 'Metal', note: 'Gold is yellow because its electrons move fast enough for relativity to matter — the effect shifts its absorption from ultraviolet into blue. Nearly every other metal is grey; gold is a visible consequence of Einstein.' },
    { name: 'Copper', hex: '#B87333', origin: 'Metal' },
    { name: 'Bronze', hex: '#CD7F32', origin: 'Metal' },
    { name: 'Brass', hex: '#B5A642', origin: 'Metal' },
    { name: 'Pewter', hex: '#899499', origin: 'Metal' },
    { name: 'Platinum', hex: '#E5E4E2', origin: 'Metal' },
    { name: 'Steel', hex: '#71797E', origin: 'Metal' },
    { name: 'Rose Gold', hex: '#B76E79', origin: 'Metal' },
];

/* ── Modern / digital vernacular ─────────────────────────────────────── */
const MODERN: NamedColor[] = [
    { name: 'Hyperlink Blue', hex: '#0000EE', origin: 'Modern', note: 'The browser default for an unvisited link since Mosaic. Nobody designed it as a colour decision — it was simply a legible blue that was not black, and the whole web inherited it.' },
    { name: 'Visited Purple', hex: '#551A8B', origin: 'Modern', note: 'The other half of that default: the link you already clicked. Two colours that shaped how a generation read.' },
    { name: 'Terminal Green', hex: '#33FF33', origin: 'Modern', note: 'P1 phosphor green — the coating on early CRTs, chosen because the human eye resolves green detail best and the phosphor was cheap and long-lasting.' },
    { name: 'Phosphor Green', hex: '#4AF626', origin: 'Modern' },
    { name: 'Amber Terminal', hex: '#FFB000', origin: 'Modern', note: 'The alternative monochrome CRT, sold in Europe on claims of less eye strain. It never had the evidence, but it had the reputation.' },
    { name: 'Neon Green', hex: '#39FF14', origin: 'Modern' },
    { name: 'Volt', hex: '#CEFF00', origin: 'Modern' },
    { name: 'Vaporwave Pink', hex: '#FF6AD5', origin: 'Modern' },
    { name: 'Hot Magenta', hex: '#FF1DCE', origin: 'Modern' },
    { name: 'Electric Violet', hex: '#8F00FF', origin: 'Modern' },
    { name: 'Majorelle Blue', hex: '#6050DC', origin: 'Heritage', note: 'The blue Jacques Majorelle painted his Marrakech garden in the 1930s. Yves Saint Laurent bought the garden decades later to stop it being demolished.' },
    { name: 'Han Blue', hex: '#446CCF', origin: 'Pigment' },
    { name: 'Ultramarine Blue', hex: '#4166F5', origin: 'Modern' },
    { name: 'Cobalt', hex: '#0047AB', origin: 'Pigment' },
    { name: 'Slate', hex: '#708090', origin: 'Nature' },
];

/* ── Coverage ─────────────────────────────────────────────────────────────
   Established names filling the gaps the sections above leave — mostly through
   the blues, violets, browns and greys, where a colour sampled off a piece of
   art would otherwise land a long way from anything named. Every one is a real,
   documented name at a documented value; none is invented to pad the shelf. */
const COVERAGE: NamedColor[] = [
    /* Blues + cyans */
    { name: 'Absolute Zero', hex: '#0048BA', origin: 'Modern' },
    { name: 'Zaffre', hex: '#0014A8', origin: 'Pigment', note: 'Roasted cobalt ore, the raw material smalt was made from. It was a trade good in its own right long before anyone isolated the metal.' },
    { name: 'Resolution Blue', hex: '#002387', origin: 'Modern' },
    { name: 'Catalina Blue', hex: '#062A78', origin: 'Modern' },
    { name: 'Duke Blue', hex: '#00009C', origin: 'Heritage' },
    { name: 'Palatinate Blue', hex: '#273BE2', origin: 'Heritage' },
    { name: 'Blue (RYB)', hex: '#0247FE', origin: 'Modern', note: 'The blue primary of the red-yellow-blue wheel taught in art rooms — a model that predates any understanding of how light or ink actually mix, and survives on tradition.' },
    { name: 'Neon Blue', hex: '#4666FF', origin: 'Modern' },
    { name: 'Bluetiful', hex: '#3C69E7', origin: 'Modern', note: 'Crayola retired Dandelion in 2017 and put the replacement blue to a public vote. "Bluetiful" won.' },
    { name: 'Savoy Blue', hex: '#4B61D1', origin: 'Heritage' },
    { name: 'Violet-Blue', hex: '#324AB2', origin: 'Modern' },
    { name: 'Liberty', hex: '#545AA7', origin: 'Modern' },
    { name: 'Purple Navy', hex: '#4E5180', origin: 'Modern' },
    { name: 'Space Cadet', hex: '#1D2951', origin: 'Modern' },
    { name: 'Independence', hex: '#4C516D', origin: 'Modern' },
    { name: 'Glaucous', hex: '#6082B6', origin: 'Nature', note: 'The botanical word for the waxy blue-grey bloom on a plum, a grape or a cabbage leaf — a colour that rubs off on your thumb.' },
    { name: 'Cool Grey', hex: '#8C92AC', origin: 'Modern', alt: ['cool gray'] },
    { name: 'Berkeley Blue', hex: '#003262', origin: 'Heritage' },
    { name: 'Blue Sapphire', hex: '#126180', origin: 'Nature' },
    { name: 'Teal Blue', hex: '#367588', origin: 'Nature' },
    { name: 'Cadet', hex: '#536872', origin: 'Modern' },
    { name: 'Deep Space Sparkle', hex: '#4A646C', origin: 'Modern' },
    { name: 'Cadet Grey', hex: '#91A3B0', origin: 'Modern', alt: ['cadet gray'] },
    { name: 'Air Superiority Blue', hex: '#72A0C1', origin: 'Heritage' },
    { name: 'Blue Yonder', hex: '#5072A7', origin: 'Heritage' },
    { name: 'Queen Blue', hex: '#436B95', origin: 'Modern' },
    { name: 'Cyan Azure', hex: '#4E82B4', origin: 'Modern' },
    { name: 'Tufts Blue', hex: '#3E8EDE', origin: 'Heritage' },
    { name: 'Bleu de France', hex: '#318CE7', origin: 'Heritage' },
    { name: 'True Blue', hex: '#0073CF', origin: 'Modern' },
    { name: 'Blue (Crayola)', hex: '#1F75FE', origin: 'Modern' },
    { name: 'Little Boy Blue', hex: '#6CA0DC', origin: 'Modern' },
    { name: 'Argentinian Blue', hex: '#6CB4EE', origin: 'Heritage' },
    { name: 'Vista Blue', hex: '#7C9ED9', origin: 'Modern' },
    { name: 'Ceil', hex: '#92A1CF', origin: 'Modern' },
    { name: 'Blue Bell', hex: '#A2A2D0', origin: 'Nature' },
    { name: 'Cerulean Frost', hex: '#6D9BC3', origin: 'Modern' },
    { name: 'Pale Cerulean', hex: '#9BC4E2', origin: 'Modern' },
    { name: 'Columbia Blue', hex: '#B9D9EB', origin: 'Heritage' },
    { name: 'Beau Blue', hex: '#BCD4E6', origin: 'Modern' },
    { name: 'Uranian Blue', hex: '#AFDBF5', origin: 'Modern' },
    { name: 'Water', hex: '#D4F1F9', origin: 'Nature' },
    { name: 'Celeste', hex: '#B2FFFF', origin: 'Nature' },
    { name: 'Turquoise Blue', hex: '#00FFEF', origin: 'Nature' },
    { name: 'Maximum Blue', hex: '#47ABCC', origin: 'Modern' },
    { name: 'Ball Blue', hex: '#21ABCD', origin: 'Heritage' },
    { name: 'Pacific Blue', hex: '#1CA9C9', origin: 'Modern' },
    { name: 'Blue Green', hex: '#0D98BA', origin: 'Modern' },
    { name: 'Munsell Blue', hex: '#0093AF', origin: 'Modern', note: 'From Albert Munsell\'s 1905 colour system — the first attempt to order colour by hue, value and chroma on a measurable solid rather than by taste. Every modern colour space owes it something.' },
    { name: 'Steel Teal', hex: '#5F8A8B', origin: 'Modern' },
    { name: 'Skobeloff', hex: '#007474', origin: 'Modern' },
    { name: 'Myrtle Green', hex: '#317873', origin: 'Nature' },
    { name: 'Rich Black', hex: '#004040', origin: 'Modern', note: 'In print, "rich black" means black ink laid over cyan, magenta and yellow — plain black alone looks washed out on a big area. The name is a press term that leaked into screens.' },

    /* Violets + purples */
    { name: 'Violet (Colour Wheel)', hex: '#7F00FF', origin: 'Modern', alt: ['violet color wheel'] },
    { name: 'French Violet', hex: '#8806CE', origin: 'Modern' },
    { name: 'Veronica', hex: '#A020F0', origin: 'Nature' },
    { name: 'Grape', hex: '#6F2DA8', origin: 'Nature' },
    { name: 'Purple Heart', hex: '#69359C', origin: 'Heritage' },
    { name: 'Royal Purple', hex: '#7851A9', origin: 'Heritage' },
    { name: 'Ultra Violet', hex: '#645394', origin: 'Modern' },
    { name: 'Dark Byzantium', hex: '#5D3954', origin: 'Heritage' },
    { name: 'Pomp and Power', hex: '#86608E', origin: 'Heritage' },
    { name: 'Chinese Violet', hex: '#856088', origin: 'Heritage' },
    { name: 'Purpureus', hex: '#9A4EAE', origin: 'Heritage' },
    { name: 'Lavender Indigo', hex: '#9457EB', origin: 'Modern' },
    { name: 'Rich Lavender', hex: '#A76BCF', origin: 'Modern' },
    { name: 'African Violet', hex: '#B284BE', origin: 'Nature' },
    { name: 'Bright Lilac', hex: '#D891EF', origin: 'Nature' },
    { name: 'Phlox', hex: '#DF00FF', origin: 'Nature' },
    { name: 'Steel Pink', hex: '#CC33CC', origin: 'Modern' },
    { name: 'Purple Pizzazz', hex: '#FE4EDA', origin: 'Modern' },
    { name: 'Ultra Pink', hex: '#FF6FFF', origin: 'Modern' },
    { name: 'Mauvelous', hex: '#EF98AA', origin: 'Modern' },
    { name: 'Lavender Gray', hex: '#C4C3D0', origin: 'Modern', alt: ['lavender grey'] },
    { name: 'Languid Lavender', hex: '#D6CADD', origin: 'Modern' },
    { name: 'Pale Purple', hex: '#FAE6FA', origin: 'Modern' },

    /* Reds + pinks */
    { name: 'Scarlet', hex: '#FF2400', origin: 'Heritage', note: 'Originally not a colour at all but a fine cloth, from Persian saqirlat. It was so often dyed with kermes red that the cloth\'s name became the colour\'s.' },
    { name: 'Candy Apple Red', hex: '#FF0800', origin: 'Modern' },
    { name: 'Coquelicot', hex: '#FF3800', origin: 'Nature', note: 'French for the corn poppy — the flower that grew over the churned fields of the Western Front and became the remembrance emblem.' },
    { name: 'International Orange', hex: '#FF4F00', origin: 'Heritage', note: 'The Golden Gate Bridge\'s colour. The Navy wanted it painted in black and yellow stripes; the consulting architect fought for the orange-red primer it arrived in, because it stood out in fog and sat well against the hills.' },
    { name: 'Rosso Corsa', hex: '#D40000', origin: 'Heritage', note: 'Italy\'s assigned national racing colour, the same pre-war code that gave Britain green. Ferrari simply never stopped using it.' },
    { name: 'Imperial Red', hex: '#ED2939', origin: 'Modern' },
    { name: 'Fire Engine Red', hex: '#CE2029', origin: 'Modern' },
    { name: 'Chili Red', hex: '#E23D28', origin: 'Nature' },
    { name: 'Cardinal', hex: '#C41E3A', origin: 'Nature' },
    { name: 'Rose Red', hex: '#C21E56', origin: 'Nature' },
    { name: 'Cornell Red', hex: '#B31B1B', origin: 'Heritage' },
    { name: 'Rufous', hex: '#A81C07', origin: 'Nature' },
    { name: 'Red (Pigment)', hex: '#ED1C24', origin: 'Modern' },
    { name: 'Antique Ruby', hex: '#841B2D', origin: 'Nature' },
    { name: 'Big Dip O\'Ruby', hex: '#9C2542', origin: 'Modern' },
    { name: 'Wine', hex: '#722F37', origin: 'Nature' },
    { name: 'Blood Red', hex: '#660000', origin: 'Nature' },
    { name: 'Rosewood', hex: '#65000B', origin: 'Nature' },
    { name: 'Persian Plum', hex: '#701C1C', origin: 'Nature' },
    { name: 'Chocolate Cosmos', hex: '#58111A', origin: 'Nature' },
    { name: 'Bulgarian Rose', hex: '#480607', origin: 'Nature' },
    { name: 'Dark Sienna', hex: '#3C1414', origin: 'Pigment' },
    { name: 'Raspberry', hex: '#E30B5C', origin: 'Nature' },
    { name: 'French Rose', hex: '#F64A8A', origin: 'Nature' },
    { name: 'Brink Pink', hex: '#FB607F', origin: 'Modern' },
    { name: 'Salmon Pink', hex: '#FF91A4', origin: 'Nature' },
    { name: 'Tickle Me Pink', hex: '#FC89AC', origin: 'Modern' },
    { name: 'Nadeshiko Pink', hex: '#F6ADC6', origin: 'Heritage' },
    { name: 'Cherry Blossom Pink', hex: '#FFB7C5', origin: 'Nature' },
    { name: 'Carnation Pink', hex: '#FFA6C9', origin: 'Nature' },
    { name: 'Cotton Candy', hex: '#FFBCD9', origin: 'Modern' },
    { name: 'Piggy Pink', hex: '#FDDDE6', origin: 'Modern' },
    { name: 'Pink Lace', hex: '#FFDDF4', origin: 'Modern' },

    /* Oranges + browns */
    { name: 'Burnt Orange', hex: '#CC5500', origin: 'Nature' },
    { name: 'Sinopia', hex: '#CB410B', origin: 'Pigment', note: 'A red earth from Sinope on the Black Sea, used for the underdrawing beneath a fresco. Strip the plaster off an Italian wall and the sinopia sketch is still there underneath.' },
    { name: 'Mahogany', hex: '#C04000', origin: 'Nature' },
    { name: 'Tawny', hex: '#CD5700', origin: 'Nature' },
    { name: 'Alloy Orange', hex: '#C46210', origin: 'Modern' },
    { name: 'Flame', hex: '#E25822', origin: 'Nature' },
    { name: 'Portland Orange', hex: '#FF5A36', origin: 'Modern' },
    { name: 'Giants Orange', hex: '#FE5A1D', origin: 'Heritage' },
    { name: 'Princeton Orange', hex: '#F58025', origin: 'Heritage' },
    { name: 'Deep Saffron', hex: '#FF9933', origin: 'Dye' },
    { name: 'Fulvous', hex: '#E48400', origin: 'Nature' },
    { name: 'Harvest Gold', hex: '#DA9100', origin: 'Modern' },
    { name: 'Golden Brown', hex: '#996515', origin: 'Nature' },
    { name: 'Field Drab', hex: '#6C541E', origin: 'Heritage' },
    { name: 'Coffee', hex: '#6F4E37', origin: 'Nature' },
    { name: 'Coyote Brown', hex: '#81613C', origin: 'Heritage' },
    { name: 'Drab Dark Brown', hex: '#4A412A', origin: 'Heritage' },
    { name: 'Bole', hex: '#79443B', origin: 'Pigment', note: 'A fine red clay laid under gold leaf to warm it and give the burnisher something to bite on. Gilding on old altarpieces glows red where the gold has worn through.' },
    { name: 'Chestnut', hex: '#954535', origin: 'Nature' },
    { name: 'Redwood', hex: '#A45A52', origin: 'Nature' },
    { name: 'Russet', hex: '#80461B', origin: 'Nature' },
    { name: 'Liver', hex: '#674C47', origin: 'Nature' },
    { name: 'Dark Liver', hex: '#534B4F', origin: 'Nature' },
    { name: 'Beaver', hex: '#9F8170', origin: 'Nature' },
    { name: 'Pastel Brown', hex: '#836953', origin: 'Modern' },
    { name: 'Shadow', hex: '#8A795D', origin: 'Modern' },
    { name: 'Cinereous', hex: '#98817B', origin: 'Nature' },
    { name: 'Dark Vanilla', hex: '#D1BEA8', origin: 'Nature' },
    { name: 'Almond', hex: '#EED9C4', origin: 'Nature' },
    { name: 'Dutch White', hex: '#EFDFBB', origin: 'Nature' },
    { name: 'Parchment', hex: '#F1E9D2', origin: 'Heritage' },

    /* Greens */
    { name: 'Go Green', hex: '#00AB66', origin: 'Modern' },
    { name: 'Green (Munsell)', hex: '#00A877', origin: 'Modern' },
    { name: 'Jungle Green', hex: '#29AB87', origin: 'Nature' },
    { name: 'Mountain Meadow', hex: '#30BA8F', origin: 'Nature' },
    { name: 'Caribbean Green', hex: '#00CC99', origin: 'Nature' },
    { name: 'Ocean Green', hex: '#48BF91', origin: 'Nature' },
    { name: 'Erin', hex: '#00FF40', origin: 'Modern' },
    { name: 'Harlequin', hex: '#3FFF00', origin: 'Modern' },
    { name: 'Bright Green', hex: '#66FF00', origin: 'Modern' },
    { name: 'Slimy Green', hex: '#299617', origin: 'Modern' },
    { name: 'India Green', hex: '#138808', origin: 'Heritage' },
    { name: 'Green (Pigment)', hex: '#00A550', origin: 'Modern' },
    { name: 'Cadmium Green', hex: '#006B3C', origin: 'Pigment' },
    { name: 'Castleton Green', hex: '#00563F', origin: 'Heritage' },
    { name: 'Dartmouth Green', hex: '#00693E', origin: 'Heritage' },
    { name: 'Cal Poly Green', hex: '#1E4D2B', origin: 'Heritage' },
    { name: 'Kombu Green', hex: '#354230', origin: 'Nature' },
    { name: 'Rifle Green', hex: '#444C38', origin: 'Heritage' },
    { name: 'Dark Moss Green', hex: '#4A5D23', origin: 'Nature' },
    { name: 'Black Olive', hex: '#3B3C36', origin: 'Nature' },
    { name: 'Apple Green', hex: '#8DB600', origin: 'Nature' },
    { name: 'Android Green', hex: '#A4C639', origin: 'Modern' },
    { name: 'Citron', hex: '#9FA91F', origin: 'Nature' },
    { name: 'Dark Yellow', hex: '#9B870C', origin: 'Modern' },
    { name: 'Inchworm', hex: '#B2EC5D', origin: 'Modern' },
    { name: 'Granny Smith Apple', hex: '#A8E4A0', origin: 'Nature' },
    { name: 'Turquoise Green', hex: '#A0D6B4', origin: 'Nature' },
    { name: 'Tea Green', hex: '#D0F0C0', origin: 'Nature' },
    { name: 'Key Lime', hex: '#E8F48C', origin: 'Nature' },
    { name: 'Mindaro', hex: '#E3F988', origin: 'Modern' },
    { name: 'Nyanza', hex: '#E9FFDB', origin: 'Modern' },

    /* Yellows */
    { name: 'School Bus Yellow', hex: '#FFD800', origin: 'Heritage', note: 'Standardised in 1939 at a conference that put paint chips on a wall and argued until one won. It was picked because black lettering reads on it best in the half-light of early morning.' },
    { name: 'Tangerine Yellow', hex: '#FFCC00', origin: 'Modern' },
    { name: 'Cyber Yellow', hex: '#FFD300', origin: 'Modern' },
    { name: 'Mikado Yellow', hex: '#FFC40C', origin: 'Modern' },
    { name: 'Jonquil', hex: '#F4CA16', origin: 'Nature' },
    { name: 'Selective Yellow', hex: '#FFBA00', origin: 'Heritage', note: 'The yellow of French headlamps, mandatory there from 1936 to 1993 — the filter cuts blue light, which scatters most in fog.' },
    { name: 'UCLA Gold', hex: '#FFB300', origin: 'Heritage' },
    { name: 'Xanthous', hex: '#F1B42F', origin: 'Modern' },
    { name: 'Earth Yellow', hex: '#E1A95F', origin: 'Nature' },
    { name: 'Sunray', hex: '#E3AB57', origin: 'Modern' },
    { name: 'Icterine', hex: '#FCF75E', origin: 'Modern' },
    { name: 'Laser Lemon', hex: '#FFFF66', origin: 'Modern' },
    { name: 'Electric Yellow', hex: '#FFFF33', origin: 'Modern' },

    /* Whites + greys + blacks */
    { name: 'Cosmic Latte', hex: '#FFF8E7', origin: 'Modern', note: 'The average colour of the universe, computed in 2002 from the light of 200,000 galaxies. The team ran a naming competition; "cosmic latte" beat "univeige".' },
    { name: 'Baby Powder', hex: '#FEFEFA', origin: 'Modern' },
    { name: 'Anti-Flash White', hex: '#F2F3F4', origin: 'Heritage', note: 'Painted on nuclear bombers to reflect the thermal flash of their own weapon. A colour chosen to survive the thing it was carrying.' },
    { name: 'Timberwolf', hex: '#DBD7D2', origin: 'Modern' },
    { name: 'Silver Sand', hex: '#BFC1C2', origin: 'Modern' },
    { name: 'Spanish Gray', hex: '#989898', origin: 'Modern', alt: ['spanish grey'] },
    { name: 'Battleship Grey', hex: '#848482', origin: 'Heritage', alt: ['battleship gray'] },
    { name: 'Nickel', hex: '#727472', origin: 'Metal' },
    { name: 'Sonic Silver', hex: '#757575', origin: 'Modern' },
    { name: 'Granite Gray', hex: '#676767', origin: 'Nature', alt: ['granite grey'] },
    { name: 'Arsenic', hex: '#3B444B', origin: 'Modern' },
    { name: 'Outer Space', hex: '#414A4C', origin: 'Modern' },
    { name: 'Dark Charcoal', hex: '#333333', origin: 'Modern' },
    { name: 'Raisin Black', hex: '#242124', origin: 'Modern' },
    { name: 'Chinese Black', hex: '#111111', origin: 'Modern' },
    { name: 'Licorice', hex: '#1A1110', origin: 'Nature' },
];

/** The whole vocabulary, in one list. Deduped by name at build time. */
export const NAMED_COLORS: NamedColor[] = (() => {
    const seen = new Set<string>();
    const out: NamedColor[] = [];
    for (const c of [...CSS_COLORS, ...PIGMENTS, ...DYES, ...HERITAGE, ...NATURE, ...METALS, ...MODERN, ...COVERAGE]) {
        const key = c.name.toLowerCase();
        if (seen.has(key)) continue;
        seen.add(key);
        out.push(c);
    }
    return out;
})();
